### ISSUE TITLE
Transformation affects undefined sibling field?

### ISSUE THREAD

**Issue by brandon-leapyear** [jquense/yup#1063]
**Describe the bug**

Given an object schema with one optional field and another field, like
```
yup.object({
  a: yup.string(),
  b: ...
})
```
If `b` doesn't have a `.transform()` function, then `.validate({ a: undefined })` returns an object with the `a` property set to `undefined`. But if `b` does have a `.transform()` function that returns a value different from the original value, the validated object does not have the `a` property.

**To Reproduce**

https://codesandbox.io/s/vigorous-bas-2p763?file=/src/index.test.js

**Expected behavior**
I would expect that no matter how `b` is configured, `a` would not be affected.

**Platform (please complete the following information):**

**Additional context**

**Comment by jquense** [comment]
oo interesting inconsistency. So what's happening is during object casting (which happens when validating) `undefined` fields are left off the resulting object. However, as an optimizations, if casting doesn't produce any changes, the original value is returned allowing `obj === schemaWithNoTransforms().cast(obj)` to work.

Not sure if this is nicely fixable...may be a simple matter of checking hasOwnProperty vs undefined.

**Comment by brandon-leapyear** [comment]
> So what's happening is during object casting (which happens when validating) undefined fields are left off the resulting object.

Why is that the case? Is it just that in the current implementation, it can't differentiate between an explicit `undefined` and the key not existing?
