### ISSUE TITLE
email validation allows сyrillic alphabet, but should not

### ISSUE THREAD

**Issue by Kadchenko** [jquense/yup#1067]
**Describe the bug**
Email validation allows сyrillic alphabet, but should not (f.e пример@mail.com should be not valid, but it is valid)

**To Reproduce**
Type email with сyrillic alphabet (f.e пример@mail.com)

**Expected behavior**
Email with сyrillic alphabet (f.e пример@mail.com) should be invalid

**Additional context**
The regular expression provided by Microsoft within ASP.NET MVC works like a charm:
/^[\w-]+(\.[\w-]+)*@([a-z0-9-]+(\.[a-z0-9-]+)*?\.[a-z]{2,6}|(\d{1,3}\.){3}\d{1,3})(:\d{4})?$/i

**Comment by knicola** [comment]
email validation depends on the RFC more than anything else. See https://en.wikipedia.org/wiki/Email_address#Internationalization_examples

I don't think it's a bad thing since in most cases you would want to send an email confirmation anyway. if it fails to send or if no confirmation is received then you can remove the account.
