### ISSUE TITLE
Only include the lodash packages that are used

### ISSUE THREAD

**Issue by jaredpalmer** [jquense/yup#107]
```
npm i lodash.mapvalues lodash.keys lodash.union ...etc
```
then remove lodash

**Comment by jquense** [comment]
in most cases that ends up creating a _larger_ package than cherry-picking from `lodash`. The main package automatically shares all required sub dependencies with little or no overlap, and doesn't rely on npm/yarn deduping them effectively. Using the main lodash is also more likely to get reuse/dedupes in an app or other library since the main 'lodash' package is a lot more popular then installing each module.

**Comment by jaredpalmer** [comment]
Fair enough
