### ISSUE TITLE
Manual invalidation

### ISSUE THREAD

**Issue by nicholaswyoung** [jquense/yup#11]
Is it possible to do something like:

```javascript
// schema is a `yup.shape()` object.
schema.invalidate('path', 'error message');
```

I'm working on a new project where manual invalidation could be very helpful. In my head this (potential) API would work regardless if the schema has already been validated or not.

**Comment by jquense** [comment]
Hey there, thanks for the issue, Sorry I am not quite following what you are trying to do here. What does `invalidate()` do, and in what context might you use it?

**Comment by nicholaswyoung** [comment]
So, let's say I have a schema. Maybe it validates because all of the keys are present -- but something else goes wrong later in the save process of my data... Maybe it doesn't correctly persist because of a unique index error.

In this case, I would like to invalidate the path that caused the error, using Yup, so I'm able to still use the ValidationError object provided by the library. 

In short, this would be a way to mark a field as invalid, manually, from any outside code that happens to use Yup as its validation engine.

**Comment by jquense** [comment]
There isn't but i I am not sure how that would make sense (maybe I need an example). the schema doesn't hold any state about whether it is valid or not because the schema can't be valid or invalid only the value passed to it can.

If I invalidated a path on the schema, what would happen if i call `schema.validate()` on some different object or value? Or are you are saying that calling `invalidate()` should throw an error? In which case you can just create and throw your own `ValidationError` since it is exported on the main yup object.
