### ISSUE TITLE
Should yup.string() validate true for objects?

### ISSUE THREAD

**Issue by geoffmschaller** [jquense/yup#1105]
I know the following is true in JS:

```javascript
{}.toString() // '[object object]'
```
But does it make sense that the yup does the following?
```javascript
yup.object().shape({
    firstName: yup.string(),
    lastName: yup.string()
}).validate({
    firstName: 'myName', // validates true
    lastName: {} // also validates true
});
```
True, in JS an object can be converted to a string, but for the sake of user input validation doesn't it make more sense that yup would validate this as false? Is string conversion really appropriate here?

**Comment by jquense** [comment]
This has been discussed before, and yes this is bad behavior. Ideally it should only succeed in casting to strings things that return reasonable string representations when coerced (arrays are an interesting gray area). The issue is just no one has had the time to implement the more complicated check

**Comment by geoffmschaller** [comment]
Would it be alright if I took a stab at it and issue a PR?

**Comment by jquense** [comment]
Yeah go for it
