### ISSUE TITLE
Required boolean type works more like defined?

### ISSUE THREAD

**Issue by krotovic** [jquense/yup#1115]
I would like to know why this works (actually I know from the source code why it works but I'd expect it not to):

```js
const schema = yup.bool().required();
await schema.isValid(false); // true
```

See runkit https://runkit.com/krotovic/yup-bool-required

Instead I have to write this:

```js
const schema = yup.bool().oneOf([true]);
await schema.isValid(false); // false
```

**Comment by jquense** [comment]
because `false` is not an empty value like `0` is not a missing number. required _is_ inconsistent but string and array are the inconsistent ones. Strings because form inputs use `''` as empty value and it's a convenience for working with them, and arrays length handling was a bad choice i made early one and it sort of stuck

**Comment by krotovic** [comment]
Ok, it just took me a while to figure this out. I would suggest to create some method for that to distinguish it just for the BooleanSchema at least. Something like `yup.bool().onlyTrue()` might work.
