### ISSUE TITLE
bug after update 0.31.1 -> 0.32.0

### ISSUE THREAD

**Issue by TrejGun** [jquense/yup#1140]
**Describe the bug**
types seems to be broken

<img width="654" alt="Screen Shot 2020-12-04 at 9 28 14 AM" src="https://user-images.githubusercontent.com/185285/101110025-18021400-3613-11eb-88c0-a6b0580d0bd8.png">

**To Reproduce**

```ts
import * as Yup from "yup";

export const validationSchema = Yup.object().shape({
  email: Yup.string(),
});

```

**Expected behavior**
No types error

**Additional context**
i was using 0.31.1 with @types/yup but 0.32.0 does not need them

**Comment by kirintwn** [comment]
Same here, forced to rollback to 0.31.1 for now.

**Comment by Cyral** [comment]
Also had to roll back

**Comment by lednhatkhanh** [comment]
Same here, had to rollback

**Comment by Cyral** [comment]
The changelog indicates some kind of breaking change but the README is not updated on how to use the new imports.

👎

**Comment by msheakoski** [comment]
[TypeScript usage](https://github.com/jquense/yup/blob/master/docs/typescript.md) is linked in the README. Basically, remove @types/yup, add strictFunctionTypes:false to tsconfig.json, and maybe a couple small adjustments listed in the TypeScript guide.

**Comment by TrejGun** [comment]
i removed @types/yup
but why should i set strictFunctionTypes:false
it was working well before

**Comment by davewasmer** [comment]
@msheakoski I don't think forcing the consuming application to reduce the strictness of their type checking is an ideal solution here. If yup is unable to accurately represent it's behavior with Typescript's types, then I think the solution is to fall back to less strict typing of yup as a library (i.e. using `any`s where necessary), which lets consuming apps retain the higher degree of strictness in the rest of their code.

**Comment by msheakoski** [comment]
@davewasmer I'm just an early adopter sharing the changes that I read in the TypeScript usage docs. Let's see what the author says.

**Comment by vtrphan** [comment]
i'm having issues too, falling back to 0.31.1 for now

**Comment by MariusMeiners** [comment]
rolling back to 0.31.1 and installing @types/yup also solved it for me for now

**Comment by artpumpkin** [comment]
Same here

**Comment by jquense** [comment]
Not a bug folks. The typing needed to actually implement the library in TS requires a lot more shenanigans than writing `.d.ts` files, and at the moment require `strictFunctionTypes: false`. I appreciate that folks don't want to reduce the strict-ness of their TS project. In practice this is not as bad as it might seem. TS **already** ignores this setting for class methods and constructors and checks them bivariantly. Turning this off (in my experience at least) doesn't cause more bugs (tho it can) but does reduce the need for explicit down-casting is lots of places it's otherwise silly to need. 

To be clear though **I would be happy to remove this restriction**, I don't have endless time to tweak TS types, so can't promise that it will happen soon. If someone wants to help out more than happy to take improvements. In the meantime if the check is a deal breaker, feel free to stick with 0.31, and the DT types. **note** tho that the DT types are _less_ correct than the include ones, and (imo) more likely to lead to issues in a project than disabling this check, but everyone's milage will vary choose what works best for you!

> for now it seems like a breaking change which should come in major update

There is a ton of breaking type changes so yes it did come with a major update. 0.31.0 -> 0.32.0, that is the versioning convention used by npm and yarn for <1.0.0 projects the, left most version bumps.

**Comment by jquense** [comment]
As an addendum, `0.32.1` fixes (inadvertently) the most limiting case that needed `strictFunctionTypes`, object shapes:
 
```js
object({
  name: string()
})
```

**should now work** fine with strict on, there are a few other cases that still don't, namely some `concat()` usages, but I suspect those are easier to work around with casts in the meantime.

**Comment by MariusMeiners** [comment]
thanks for the explanation 👍

**Comment by IvanKalinin** [comment]
It also have issue with Lazy schema.

```(property) childNodes: Yup.ArraySchema<Yup.ObjectSchema<Assign<Record<string, Yup.AnySchema<any, any, any> | Reference<unknown> | Lazy<any, any>>, {
    meta: Yup.ObjectSchema<Assign<Record<string, Yup.AnySchema<any, any, any> | Reference<...> | Lazy<...>>, {
        ...;
    }>, Record<...>, TypeOfShape<...>, AssertsShape<...>>;
}>, Record<...>, TypeOfShape<...>, AssertsShape<...>>, Record<...>, TypeOfShape<...>[] | undefined, AssertsShape<...>[] | undefined>
Argument of type 'Lazy<any, unknown>' is not assignable to parameter of type 'AnySchema<any, any, any>'.
  Type 'Lazy<any, unknown>' is missing the following properties from type 'BaseSchema<any, any, any>': deps, tests, transforms, conditions, and 37 more.
```

**Comment by IvanKalinin** [comment]
![image](https://user-images.githubusercontent.com/12299212/101204047-75e92880-3620-11eb-8814-db97ce5a0229.png)

![image](https://user-images.githubusercontent.com/12299212/101204070-81d4ea80-3620-11eb-87c2-3bf30eb76d60.png)

![image](https://user-images.githubusercontent.com/12299212/101204100-91ecca00-3620-11eb-8611-b0d6b52f533a.png)

![image](https://user-images.githubusercontent.com/12299212/101204150-a8932100-3620-11eb-9cbe-1c6d58c1e13f.png)

**Comment by jquense** [comment]
open up another issue with this specific one please!

**Comment by harshzalavadiya** [comment]
There can be issue for those who are not using TypeScript in strict mode

For me I was able to temporary supress this and be on latest package by disabling typecheck only for src folder
https://stackoverflow.com/questions/40164034/typescript-strictnullchecks-with-limited-scope

is there any other way possible?, because having flexible `strictnullchecks`  might be nice instead of enforcing it on everyone

**Comment by jquense** [comment]
@harshzalavadiya yup will likely never support `strictNullChecks` being off. Yup as a validation library (and runtime type checker) makes the distinction between undefined and null and needs TS to do the same in order to be accurate

**Comment by harshzalavadiya** [comment]
@jquense okay, then enabling strict null checks is the way to go, It's a hassle for one time but might be worth

Anyway thanks for all of your hard work in `yup` you are doing amazing job :+1:

**Comment by mikecousins** [comment]
Switching to any or AnySchema don't work with Formik:

![image](https://user-images.githubusercontent.com/725614/102151070-3c3dcc00-3e2f-11eb-883a-c7e7e259b626.png)

![image](https://user-images.githubusercontent.com/725614/102151081-419b1680-3e2f-11eb-9e60-8410b13f57c2.png)

**Comment by jquense** [comment]
Formik needs to update the types it's using
