### ISSUE TITLE
Compile functionality

### ISSUE THREAD

**Issue by sebasgarcep** [jquense/yup#119]
One of the cool aspects of joi is that  one could define validation using a shorthand syntax and then run it through compile and it will get turned into a joi schema. Is this possible with yup?

**Comment by jquense** [comment]
Hi there. That's not something that's built in to yup, but there isn't any technical reason why it couldn't be built as a helper. Yup doesn't include that because it's a bunch of extra code that doesn't add a lot a of value apart from a terser api, which is cool but not worth the the extra weight in my opinion.

**Comment by sebasgarcep** [comment]
@jquense I agree. Before closing, I'm thinking on implementing this but for it to work I would need a way to know if something is a normal object or a yup schema. Is this possible right now?

**Comment by jquense** [comment]
yes! `yup.isSchema(object) // => true for yup schemas`

**Comment by sebasgarcep** [comment]
Nice! Thanks for your help @jquense.

**Comment by Peracek** [comment]
I'd like to use yup for form validation on frontend but the form structure is dynamic and comes from backend. The compile functionality would be really beneficial here.
