### ISSUE TITLE
Minor version update contains breaking TypeScript changes

### ISSUE THREAD

**Issue by mrlubos** [jquense/yup#1201]
**Describe the bug**
Attempting to update from `0.30.0` to `0.32.8` completely crashes a TypeScript project to the point where it appears every single form definition needs to be rewritten from scratch.

**To Reproduce**

It's hard to create a simple, reproducible case, though I might attempt to do that if desired. I have some custom functions for bundling validation behaviour, e.g. I have a function applying regex on `string()` used to validate passwords or emails. These functions have broken response type definitions.

Further, I have form schema definitions roughly defined like this.

```tsx
export const useSchema = (): ObjectSchema<FormValues> => {
  return object({
    foo: string().required(),
    bar: string().required(),
  }).defined();
};
```

These no longer work, either. Replacing `ObjectSchema` with `SchemaOf` and `object({ ... })` with `object().shape({ ... })` fixes the immediate errors in the file, but throws when plugged into the actual form handler. I use `react-hook-form` with `@hookform/resolvers/yup`.

```tsx
useForm({
  defaultValues: getDefaultValues(),
  resolver: yupResolver(useSchema()), // this line fails to compile
});
```

Even if I manage to get past this issue, I run into another problem with fields that cannot be null when submitted but can be null when initialised. Image a required yes/no question which isn't initialised to any choice. I initialise it with `null` and if I try to submit, Yup should catch it if it's not `boolean`. This behaviour worked before, and maybe still works, but now TypeScript complains about incorrect types.

Lastly, I created a completely custom method on `ArraySchema`. This throws in compiler, too, but I gave up on upgrading before getting to the root cause of that one.

**Expected behavior**

A minor version upgrade shouldn't break so many parts of the application. If it does, there should be a clear documentation on how to upgrade to the latest version.

**Comment by jquense** [comment]
A few things, first, sorry that upgrading has been a pain. Second, the convention for the npm ecosystem for projects that are pre v1 is that the left-most non zero version is the "major" one, and yup follows this convention. So one should read 0.30 - 0.32 as two major version bumps.

> every single form definition needs to be rewritten from scratch.

That is mostly correct. I didn't maintain or write the other DT yup types though. prior to v0.32.0 yup had no official types. I would suggest reading through the typescript docs https://github.com/jquense/yup/blob/master/docs/typescript.md they provide some more context. Overall the types are very different but the changes needed to go from DT to the built-in ones end up not being too bad. We moved a very large project that had 700+ errors with only a few replacements of ObjectSchema and InferType usages, but YMMV depending on how you used the DT types.

**Comment by mrlubos** [comment]
Hey @jquense, thank you for the prompt reply! Agree on the pre v1 point, although `yup` has been around for 4½ years and nowhere in the README does it say its API is experimental or beta, so I just assumed that's how versioning goes here (many projects don't strictly follow the semver convention).

I also understand the type definitions issue, although my wishful thinking is you would've used the existing types as a starting point and progressively introduced breaking changes on top of them. As it is, I am unsure whether it's possible to upgrade at all, perhaps the issue is with the `react-hook-form` integration itself rather than updating `yup` on its own.

**Comment by jquense** [comment]
the versioning shouldn't indicate experimental or unstable, the actual semver spec says "anything goes" for pre v1, so yup (and npm generally) is _more_ structured than the semver spec. e.g. you can rely on yup's versioning to communicate breaking changes exactly the same way you would a v1+ semver project. The only difference is the digit that is bumped. That said yup doesn't make huge breaking changes often or lightly. the most recent two changes are actually an attempt to make this more incremental. `0.31.0` introduces a few small, but breaking behavior changes. `0.32.0` the breaking type behavior so that one could upgrade and ensure the behavior in apps still worked before changing to the new types and messing with them.

> my wishful thinking is you would've used the existing types as a starting point and progressively introduced breaking changes on top of them

I agree that this would better, but given the nature of type defs it was basically impossible to do that. Any change to the base type requires changes through everything. and the schema typing is most of the library. It should absolutely be possible to upgrade (we've done it from the DT types on a few large projects) it may require the RHF upgrade it's own defs first tho if they are using or relying on yup's types

**Comment by mrlubos** [comment]
@jquense Gotcha, I understand sometimes you have to pull the plug and break some things to make the project more stable in the long run. I will try to upgrade again in a few weeks, will see how it goes. Thank you!

**Comment by donaldpipowitch** [comment]
> > every single form definition needs to be rewritten from scratch.
> 
> That is mostly correct

Hi @jquense !

Thanks for including official typescript definitions. Do you know about a migration guide? I stumbled about stuff like:

```ts
const fileSchema = object({
  fileName: string().required(),
  id: string().required(),
});

const userSchema = object({
  myFile: fileSchema.required().nullable(),
}).defined();

type UserData = InferType<typeof userSchema>;

const userData: UserData = {
  myFile: null, // null is not allowed anymore
};
```

**Comment by zeing** [comment]
> ```ts
> InferType
> ```

me too, I stumbled about InferType

**Comment by zeing** [comment]
> > > every single form definition needs to be rewritten from scratch.
> > 
> > 
> > That is mostly correct
> 
> Hi @jquense !
> 
> Thanks for including official typescript definitions. Do you know about a migration guide? I stumbled about stuff like:
> 
> ```ts
> const fileSchema = object({
>   fileName: string().required(),
>   id: string().required(),
> });
> 
> const userSchema = object({
>   myFile: fileSchema.required().nullable(),
> }).defined();
> 
> type UserData = InferType<typeof userSchema>;
> 
> const userData: UserData = {
>   myFile: null, // null is not allowed anymore
> };
> ```

me too, I stumbled about InferType

**Comment by stilllife00** [comment]
> The only difference is the digit that is bumped

@jquense Chiming in since I experience recently the same breaking changes problem between 0.30.0 and 0.31.0 on the `array().required()` and I did not imagine that it would be a breaking change. But you are right (and thanks for explaining well) about the npm versioning logic and documenting the changes on the changelog. That helped in the fix and I have learnt something new.

My question is: since most of the libraries are following semver and people got used to the fact that the second number is a non-breaking change, what stops `yup` from bumping to `1.0.0` and follow the most commonly used approach to avoid issues like this in the future?
