### ISSUE TITLE
Different rules for validating array items

### ISSUE THREAD

**Issue by marionram** [jquense/yup#1297]
Hello. I'm new to Formik and Yup. I would like to validate the array values from the following object
```
view: { center[lng, lat] } // lng lat are numeric values i.e. [-123.43, 54.32]
```
The lng lat values are displayed in 2 text fields and I need to validate that the user doesn't enter a coordinate value that's out of bounds.
This is the logic that I'm trying to implement in my validation schema but no errors show up when I test with values out of bounds
```
//lng must be between -180 and 180. lat must be between -90 and 90
// [-183, -93] => no error triggered on either value
const validationSchema = Yup.object().shape({
view: Yup.object().shape({
      center: Yup.array(),
      'center[0]': Yup.number().test('test-0', 'test-msg', function (value) {
         if (value > 180 && value < -180) {
            return this.createError({ message: `Out of bounds (1)` })
         }
      }),
      'center[1]': Yup.number().test('test-1', 'test-msg', function (value) {
         if (value > 90 && value < -90) {
            return this.createError({ message: `Out of bounds (2)` })
         }
      }),
   })
});
```
I've also tried the following and an error is triggered but only for center[0]. 
```
const validationSchema = Yup.object().shape({
view: Yup.object().shape({
      center: Yup.array()
         .of(
            Yup.number().required('Enter a numeric value').min(-180, "min error 1"),
            Yup.number().required('Enter a numeric value').min(-90, "min error 2"),
         ),
   }),
});
```
Changing the code above to `.of(Yup.number().required())` will work to validate that both values are numeric but that's not what I'm looking for.

Is validation on `center[0]` and `center[1]` as different rules even possible? 
Any advice on this would be appreciated, thanks.

**Comment by jakobsandberg** [comment]
@marionram in your first code block, the conditional statements will never be true, e.g. no number is both greater than 180 and less than -180. Additionally, the function we pass into `test()` needs to return a boolean. In this case, we are returning either `undefined` or the result of `this.createError`.

In your second code block, the method `array.of()` takes in a single argument, thus the error is only being triggered for `center[0]`. This method is used for validating arrays containing only elements of the same schema. In this case, latitude and longitude have different requirements and thus will likely need different schemas.

I recommend using the built-in `number.min()` and `number.max()` methods over `mixed.test()` if all you care about are min and max values. I also recommend modeling `center` as an object with `longitude` and `latitude` as keys rather than an array. Then, the schema is quite simple

```javascript
const validationSchema = Yup.object({
  view: Yup.object({
    center: Yup.object({
      longitude: Yup.number().min(-180).max(180),
      latitude: Yup.number().min(-90).max(90),
    })
  })
});
```

**Comment by marionram** [comment]
Thank you so much for your response @jakobsandberg. 
You're right, my logic in the first code block was wrong. I'll keep that in mind next time I use `test()`
Changing `center` to be an object definitely made things easier and the validation is working now!
