### ISSUE TITLE
Object validation order

### ISSUE THREAD

**Issue by tkvw** [jquense/yup#143]
Is it possible to define the order in which the properties of an object are validated? 
In this example I want to enforce first is run before second. 
```
const toCheck = {second: .., first: ...}
object({
   first: firstSchema,
   second: schemaDependsOnFirstBeingValid
}).validate(toCheck,{context: toCheck})
```

**Comment by jquense** [comment]
Fields will validate generally in the order you define them, but you you can explicitly control order via the 'when' method,  which is used for conditional schemas primarily but also just allows defining a dependency order of fields. 
 Usually tho order doesn't matter in the validation phase because the value doesn't change at that point so when you validate one or the other doesn't matter since the values are fixed at that point.

**Comment by tkvw** [comment]
👍 thanks
