### ISSUE TITLE
Yup needs its own documentation website

### ISSUE THREAD

**Issue by scientist27** [jquense/yup#1456]
### Feature request
Although many other open-source npm packages have dedicated websites for their documentation - like [Tailwind CSS](https://tailwindcss.com/), [Formik](https://formik.org/) and [Material-UI](https://material-ui.com/) - Yup's docs are still in a README file in its GitHub repository. It would be much better if Yup also migrated its own docs to a separate website.

### Why have a separate website?
Making a website for the docs can help make Yup more developer-friendly, because navigating through a website is much more intuitive than scrolling through a long markdown file. It would also allow for live code examples (for example, CodeSandbox demos) to be embedded along with the documentation. Lastly, it would help make Yup look more professional.

@jquense, if you think this is a great idea, I would love to help design and build the website!

**Comment by jquense** [comment]
Hey there thanks for the offer. A website would be be nice, but i don't think necessary for yup, i'm quite happy with the current docs in markdown, they are very easy to maintain unlike a hosted site. I maintain a lot of repos, some of which with dedicated docs sites, and it's not free to maintain. In fact it's usually significant work, and for some libraries like UI components that work is worth it, because users should be able to see and touch the UI before deciding if they want to use it. For a library like yup, it's less important, and i prefer the current set of tradeoffs.

**Comment by scientist27** [comment]
OK, I understand completely. Maintaining a website *would* be a lot of work. Anyways, thanks so much for taking the time to respond!
