### ISSUE TITLE
`test()` method always executes eventually

### ISSUE THREAD

**Issue by chioio** [jquense/yup#1554]
# When I create a custom validation with `test()` method, it always execute eventually

Here is my code:
```js
const schema = Yup.object()
    .shape({
      email: Yup.string()
        .required('Email is required!')
        .email('Email is invalid!')
        .test(
          'existed-check',
          'This email was registered!',
          () => emailCheck.isExisted,
        ),
      username: Yup.string()
        .required('Username is required!')
        .min(3, 'Username must be at least 3 characters!')
        .matches(
          /^[A-Za-z][a-zA-Z0-9_]*$/,
          'Username only allows "A-Za-z0-9_" combination!',
        )
        .test('existed-check', 'This username was registered!', () => {
          console.log('EXECUTED')
          return usernameCheck.isExisted
        }),
    })
    .required()
```

**!!!** What could I do for this situation: If the validation before the `test()` returned false, so the `test()`method do not need to execute.

**Comment by jquense** [comment]
tests are always run in parallel with their "siblings", there isn't a way to change that. There have been some proposals to add an API for controlling the sequencing but nothing settled on. Honestly tho i don't really think this is a problem yup should solve. tests should be written so that their order doesn't matter.
