### ISSUE TITLE
Website for yup with docussaurus

### ISSUE THREAD

**Issue by fernandobelotto** [jquense/yup#1575]
Hi! I found yup really helpful for my projects and i decided to created a website based on the readme for helping people use and study de library. The website right now is hosted on vercel at [https://yup-docs.vercel.app](https://yup-docs.vercel.app/). I would like to contribute in some way so i made this. What you guys think about?

**Comment by jquense** [comment]
Hey, sorry for no response. This is great! really nice work. I'm not entirely sure that maintaining a website (even with the super easy to use docusaurus) is the best idea for yup, if only because it's added work for me and i already am really short on time to spend on yup. If you want to open up a PR with it though I can think more about it 👍
