### ISSUE TITLE
Incorrect email validation for not required field

### ISSUE THREAD

**Issue by ruscoder** [jquense/yup#16]
I think email validation works incorrect.
Example:
```
yup.string().email().validate('') - invalid! 
```
I think problem in matches check - test: ```value => value == null || regex.test(value)```
In `transform` null values and empty strings transforms to '' and '' does not equals null!

**Comment by jquense** [comment]
Hi there,

Sorry I am not sure why would you expect this to work? An empty string is not a valid email address, and its not a non-string value.

if you don't want your `null` values to to be coerced to strings then, you should set the schema to be `nullable()` otherwise use `undefined` as your empty value not `null`.

**Comment by ruscoder** [comment]
Sorry, it is my mistake. `nullable()` exactly what is needed.

But how to implement validation for email when empty string is allowed too?

Thanks.
