### ISSUE TITLE
How to customize all `.number()`, `.number()` and `.required()` errors

### ISSUE THREAD

**Issue by joaocasarin** [jquense/yup#1651]
So, I have this yup object: 
```ts
const userSchema = yup.object().shape({
    name: yup.string().required('Name is required.'),
    age: yup.number().required('Age is required.'),
    password: yup.string().required('Password is required.')
});
```

One of the issues is solved by adding the custom error message to `.required()`, but when the user input is like:
```json
{
  "name": "adsa",
  "password": "1234",
  "age": "d"
}
```

Yup error is 
```json
{
	"error": "age must be a `number` type, but the final value was: `NaN` (cast from the value `\"d\"`)."
}
```

And when the age input is: `"1"`, it works, even though the input is a number in a string format.

When I add the `strict` option to the validation method, then the error for `"1"` becomes:
```json
"error": "age must be a `number` type, but the final value was: `\"1\"`."
```

With that said, how can I change that generic error from yup, or at least, if `strict` is not true, but the value inside the string is still a number, how can I cast it to number?

**Help Others Reproduce**

[Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 ](https://codesandbox.io/s/pensive-alex-x4cnwe?file=/src/index.test.js)

**Comment by jquense** [comment]
that error can be changed via the `typeError` method

**Comment by jesusrodrz** [comment]
@jquense there is a way to set the default message for all the number validation without having to use typeError on every field

**Comment by m7he4rt** [comment]
> there is a way to set the default message for all the number validation without having to use typeError on every field

any updates?

**Comment by Ryu13** [comment]
I started using yup recently for my personal project (we use it on my contract) and setting global errors has been a trial.

Note that this isn't intended to bash or anything like that, this library is pretty sweet. I think the individual field schema management is pretty well done and most of the builder pattern is well managed. However, globals seem to be lacking to a significant degree. I've done a bit digging through the library and it's possible any/all of this could be overkill for something that exists (if so, *please* point that out) but here's what I've resorted to thus far.

My use-case is I'd like the errors to be formatted based on the schema usage, such as in an array. I'm relying on the path containing '[' and update messages to something like `row X (row key value) field Y is required.` assuming your schema is used in an array context. Especially since my helper desires the actual context and schema, formatting in most ways will not work, even trying to use a mutation on typeError because params (only arg passed to `message`) never has `this` for some strange reason.

To get around this, one cumbersome way I've found is to completely clobber `typeError` and basically reimplement it using the source code minus a tweak.

```
yup.addMethod(yup.number, 'typeError', function () {
	return this.test({
                // removed message usage here and instead hardcode usage of it below but use it as you need
		name: 'typeError',
		test: function (value: number) {
			if (value !== undefined && !this.schema.isType(value)) {
                                // determine message here now that you have access to `this` and `schema`.
				const display= '';

				return this.createError({
					message: `${display} is required.`,
					params: {
						type: (this.schema as any)._type
					}
				});
			}
			return true;
		}
	});
});
```

Obviously you can reference the original source and update a different section if you want but this works for me.
This updates all typeErrors for number that I have (I'm not concerned with number -> yup.string errors, for now). I can't find a central place to also handle `min`, `max`, etc. so I similarly replace each of them with a custom test function.

Ultimately, it would be awesome to be able to override central error formatting with the `this` of testContext (which has schema, context, path, etc.).

Hopefully this helps someone in the interim.
