### ISSUE TITLE
Migration guide to v1 for "nullable()" and "required()"

### ISSUE THREAD

**Issue by donaldpipowitch** [jquense/yup#1763]
[test case](https://codesandbox.io/s/funny-lena-wb540v?file=/src/index.ts)

I'd like to define a property in an object which is properly typed as `string | null` via `InferType`, but when the value is actually `null` it should not be treated as valid (same for an empty string).
We have this use case _a lot_. If you prepopulate models with common JS APIs like `Storage.getItem()` or `URLSearchParams.get()` it will be `string | null` in many cases. I'd like to avoid using manual defaults `?? ''` and I'd would like to avoid allowing `undefined` (to ensure that I didn't forgot the property completely).

With `string().nullable().required()` `null` is not a possible type. With `string().required().nullable()` `null` is a possible type, but will be treated as valid instead of invalid.

This was possible in older versions (e.g. `0.31.1`) and I wonder how this can still be achieved with `v1`.

Thank you for working on this. 🥰

**Comment by jquense** [comment]
There are a few ways to migrate from this pattern but it often depends on what you are trying to achieve here. The cases where i've used this pattern were when i've started with something that might be nullable but should end up being nullable, specifically when casting and then validating. It sounds tho that you want a TS type that allows null even tho it doesn't actually allow null? Can I ask _why_ you end up needing that type? Even in the old versions that isn't what `validate` returns which represents the "true" type the schema asserts.

**Comment by donaldpipowitch** [comment]
>  It sounds tho that you want a TS type that allows null even tho it doesn't actually allow null? Can I ask why you end up needing that type?

Let's say you an invoicing form with an "amount" field and it is mandatory to fill it out. But you don't want to populate it with some _default amount_, because no value really makes sense and people should actively fill it out. In those cases I usually had something like `amount: number().required().nullable()` which allows me to _start_ with a `null` value, but it's not possible to pass the form without a `number`.
(It would actually be _awesome_ to also have some like `InferValidType` which gives me back a type where I _know_ `null` doesn't exist anymore. Currently we'd just write `amount!` in the submit handler of our form to tell TypeScript _"At this point we know it was validated and can't be null anymore."_.)

> Even in the old versions that isn't what validate returns which represents the "true" type the schema asserts.

Could you explain this? I have to say we usually use `yup` together with formik and its `validationSchema` property. This hides away some `yup` details I might not know. (Sometimes we already switched to a custom `validate` function if too much functionality from `yup` was hidden by formik.)

**Comment by jquense** [comment]
> Could you explain this?

In <v1 yup schema produce two types, the first `InferType` is the return value of `cast()` which used to check `nullable` distinct from `required`, the second type was the return value of `validate` which took into account `required` so you'd get:

```ts
string().nullable().required().cast(null) // string | null
string().nullable().required().validate(null) // string
```

This worked this way for exactly the reason you are outlining, forms that start with a default value that is invalid but you want to serialize via `cast()` but validate as not being `null`. However, this produces to exceedingly complex types and performance issues, as well generally being unintuitive to say something is nullable but also required. Which why we changed it.

That said, Formik doesn't depend on this pattern when using schema, it doesn't `cast` at all except when validating which is also when you don't want to accept `null` anyway. Where do you hit issues with v1 specifically? are you casting values to get defaults for the form? Are you just running into type mismatches? I ask because there are a number of ways to solve this and it's hard to say which works for you. But generally the options are:

- transform `null` to a valid empty value
- use nullable, and add a custom "notNull" validation that throws on null values (this leaves your type looser than it is)
- use the cast option 'ignore-optionality`, see: https://github.com/jquense/yup/releases/tag/v1.0.0-beta.5
- use two schema one for serializing partial values and one for validating.

I also hope to add a `deepNullable` method to objects to make marking an entire schema as nullable easier, or better yet a deep `merge` that allows changing multiple values at once

**Comment by donaldpipowitch** [comment]
>  I ask because there are a number of ways to solve this and it's hard to say which works for you.

I created a more sophisticated example which shows the usual flow we have for forms: [click here](https://codesandbox.io/s/condescending-grass-z6vdx2?file=/src/App.tsx). I'm not sure if one of the four options could be used here...?

**Comment by jquense** [comment]
Hmm Formik has bad types here...`initialState` shouldn't really be the same as the value out, since the form builds that value, and it may be incomplete (or invalid) to start. I don't have a great solution for this case since the type usage is (strictly speaking) incorrect, the input is not always assignable to the output type.  

You could solve this with just a TS type something like: `initialValue: DeepNullable<InferType<typeof schema>>`

or with runtime changes to the schema to transform `null`s to `undefined` (I know you said you didn't really like that)

**Comment by donaldpipowitch** [comment]
Did I understood correctly that `InferType` does not infer the type for the unvalidated input, but the validated input? 🤯 That would mean we used wrong all over the place. We assumed it would be for the unvalidated input, because things like `nullable().required()` includes `null` as input in the past, but disallowed it as the output.

**Comment by jquense** [comment]
Yeah it's the output, the input type for yup schema is `any`. Tbh I am surprised InferType is allowing null in these cases that seems like a bug. We do distinguish two types (see the old docs https://github.com/jquense/yup/blob/pre-v1/docs/typescript.md) but that's via TypeOf and it's not still not an input type just a different output

**Comment by donaldpipowitch** [comment]
Well, good to know. Seems like we abused a bug in the last years. Thanks for all the work and help. I'll close the ticket. Looks like we'll need to manually provide the input types from now on.

**Comment by donaldpipowitch** [comment]
Just to clarify: `Asserts` is just an alias to `InferType` and `1.0.0-beta` has no equivalent to `TypeOf` which existed in older versions. Correct? Is it planned to bring something like `TypeOf` back?

**Comment by jquense** [comment]
That's correct,

>  Is it planned to bring something like TypeOf back?

No, because there is no longer a distinction between the two types. `cast` will now always produce a valid _type_ and `validate` can't change the type shape further only make narrowing assertions on it (e.g. is this an integer, is this uppercase, etc).

You can still still create a validation that asserts things that the type doesn't reflect, if that's what you want, e.g.

```ts
yup.addMethod(Schema, 'assertPresent', function() {
  return this.test('assertPresent, 'must be present', (value, ctx) => {
     return value != null
  })
})

let schema = string().nullable().assertPresent()

schema.cast(null) // string | null

schema.validate(null) // ValidationError 'must be present'

type S = InferType<typeof schema> // string | null
```

This reproduces the same runtime behavior but leaves you with a slightly dishonest type, since technically after validating you know it's not actually null, but you can use `!` in TS to work around that

Alternatively you go the other way and replace `TypeOf` with a generic `DeepNullable` type that takes an input and marks everything as nullable for the sake of creating your default value.

**Comment by donaldpipowitch** [comment]
Thanks again.
