### ISSUE TITLE
Yup should be strict by default

### ISSUE THREAD

**Issue by rotexhawk** [jquense/yup#1780]
I am a fan of this library and I am grateful for your work. I can make the following changes if everybody agrees to it. 

I believe Yup should not pass validation if there are extra fields in the object. Specially if I am providing the shape of the schema, with `yup.shape({})` I think by default it is best to be as restrictive as possible and fail early because we don't want these bugs to make it further down the chain. I was also hoping that the strict flag would check for this case but it didn't. 

Validation is the first line of defense and letting objects pass validation with extra fields can cause security issues. 

I know about  the `.noUnknown()` but this should be by default and maybe we can add a method `allowUnknown()`.

**Comment by jquense** [comment]
Hi, we aren't going to change the default here.  I understand it's not a default for you, however there is a lot of code and other use cases they prefer this default, I personally depend on it more than I want the opposite. Yup supports what you want to do and if if having a different default is vital to you we recommend that you export your own "base" schema factories with the defaults you want:

```ts

export const strictObject = (shape) => object(shape).noUnknown()

```

**Comment by rotexhawk** [comment]
I understand that yup supports my use case and I haven't dug deep into the what kind of issues this change will create but theoretically this behavior violates the principle of validation. If I am defining a schema shape I want it to be exactly that. Like I said before, the default behavior is a security issue as well. We are allowing invalid schemas to pass validation and that's not how I think of validation. I know the other way might be easier way but it is not the correct way.

**Comment by jquense** [comment]
You are treating this as a "correctness" thing when it's not. If your objects need to be strictly limited to just the properties you define then it is up to you to define a schema that describes that requirement, same as any other requirement. Yup is not  more incorrect or unsafe because it requires you to explicitly define what you want it to do. There is no reason to say that objects should only contain defined properties is "more correct" than what it does, except that your situation requires it, and that is fine, you should use yup to define schema that match your needs. 

> We are allowing invalid schemas to pass validation

That is not what's happening, if you don't forbid extra properties the schema *is* valid, because the schema defines objects in the same way TypeScript does. What you are encountering is that yup doesn't have the default you find to be intuitive, which is fine, but it's not incorrect. I appreciate that you find this unintuitive but it's not a bug and it is unlikely to change.
