### ISSUE TITLE
Transform order of nested objects

### ISSUE THREAD

**Issue by kheyse-oqton** [jquense/yup#190]
According to this experiment, the transforms of nested objects are executed from root to leaf/parent to child.
```
function traceTransform() {
  return this.transform((value, originalValue) => {
    console.log(value);
    return value;
  });
}
yup.addMethod(yup.mixed, 'traceTransform', traceTransform);
const schema = yup.object().traceTransform().shape({
  a: yup.object().traceTransform().shape({ b: yup.number().traceTransform() })
});
console.log(schema.isValidSync({ a: { b: "9" } }));
```
result:
```
  { a: { b: "9" } }
  { b: "9" }
  9
  true
```

Wouldn't it be more useful to do it leaf to root/child to parent? This way the transform function can assume that any elements in the object have already been cast and transformed to the type defined in the schema. E.g. in this example you can see the value of "b" is still a string!

Or is there an other reason why this is not feasible?

**Comment by jquense** [comment]
It's more useful in some situations i'd agree. Generally tho, you really need to run the transformations top -> down so you can make assumpts about the object your transforming. Example:
```
let schema = object({ 
  firstName: string()
}).camelCase()

schema.cast({ FIRST_NAME: 'baz' })
```
We need to transform `FIRST_NAME` to firstName in order to know what value to pass to the string schema, otherwise we'd have to guess at the mapping of keys to child fields

**Comment by kheyse-oqton** [comment]
Thank you for the clarification. I understand.
