### ISSUE TITLE
`TypeOf` replacement in v1.0

### ISSUE THREAD

**Issue by logaretm** [jquense/yup#1914]
Hello, first of all, congratulations on the 1.0 release, and thanks for your hard work.

I have a quick question regarding the `TypeOf` type that used to be present in `v0.32` that was typed as follows:

```ts
type TypeOf<TSchema extends TypedSchema> = TSchema['__inputType'];
```

It seems to me that this `__inputType` and the input types were dropped in v1.0. 

I was sort of relying on it to provide input typing for [this](https://github.com/logaretm/vee-validate/pull/4064).

The use case here is to type the real-time values of UI inputs as a separate type from the submitted values which would be the output type.

```ts
const schema = yup.object({
  email: yup.string().email(EMAIL_MSG).required(),
  password: yup.string().min(8, MIN_MSG),
});

type Input = yup.TypeOf<typeof schema>; // { email: string | undefined, password: string | undefined }
type Output = yup.InferType<typeof schema>; // { email: string; password: string; }
```

Was this removed for the speed benefits in Typing for v1?

In case of no alternatives for 1.0 or a migration path, do you recommend using `Partial` or `PartialDeep` to get this concept of input types back? I don't think it would work as well especially since the input types (inferred by `TypeOf`) would also work well with assigned default values with `.default`. Would appreciate it if you can suggest better alternatives if possible or point me in a direction.

I'm thinking about trying to extract the default values type from a schema and recursively merge it with the output type.

**Comment by jquense** [comment]
`TypeOf` was removed yes, because it's not longer relevant to the types schema produce. It _used_ to be the value that `cast` produced, which could be looser then what `validate` allowed: see https://github.com/jquense/yup/issues/1906 for more details and migration path. There isn't always one good way to handle this situation, it depends on your use case, but generally `partial` or `deepPartial` are what you want for "the same type but with values potentially missing" as is useful in forms

**Comment by logaretm** [comment]
Thanks, we can close this since it is not really an issue. Will post what I came up with later here for future reference.

**Comment by JRebella** [comment]
@jquense what if I need the before and after types of a property that's casted/transformed from one type to another?

For example lets say I have a free-type input field where I expect the user to input a date. I can have a yup schema that first takes a `string` as "input" and then transforms it into a `Date` when the validations pass. I can get the "output" type using `InferType` but how do I get the input string type?

**Comment by jquense** [comment]
@JRebella there is no specific input type, schema take `any`, there isn't any way to say "you must only pass a string" by design since schemas value is in that they can turn anything into the right type, via transforms etc. Generally you already know the input type if it's specific. you can either use another schema to describe it, or just use typescript if you want to enforce `string`
