### ISSUE TITLE
`.addMethod` doesn't work with `lazy`

### ISSUE THREAD

**Issue by leesiongchan** [jquense/yup#194]
I have custom method `yup.date().format()` 

```javascript
const partnerSchema = yup.object().shape({
  joiningDate: yup.date().format('YYYY-MM-DD'),
});
const customerAccountSchema = yup.object().shape({
  partnerDetails: yup.lazy(() => partnerSchema.when('category', (category, schema) => category === 'PARTNER' ? schema : yup.mixed()),
});
```
When I remove the `lazy` mode, everything seems to be working great.

**Comment by jquense** [comment]
I think the problem here is that yup doesn't do "nested" resolutions like this, it resolves the return value of `lazy` which is an unresolved `when`. Perhaps you've oversimplified the example here, but it doesn't look like the lazy is necessary any way? Generally the recommendation is to use lazy or when, but you don't usually need both together since lazy is more powerful than `when`

**Comment by leesiongchan** [comment]
How to use `lazy` to refer to other property? I use `when` is because I want to get other property to do a comparison.
