### ISSUE TITLE
Yup forcing the `any` type to include `undefined` in nested schemas

### ISSUE THREAD

**Issue by szebert** [jquense/yup#2070]
**To Reproduce**
```
import { ObjectSchema, mixed, object } from 'yup';

interface Test1 {
  input: any;
}

const test1Schema: ObjectSchema<Test1> = object({
  input: mixed().required(),
});

export interface Test2 {
  test1: Test1;
}

export const test2Schema: ObjectSchema<Test2> = object({
  test1: test1Schema.required(),
});
```

Typescript error:
Type 'ObjectSchema<{ test1: { input?: any; }; }, AnyObject, { test1: any; }, "">' is not assignable to type 'ObjectSchema<Test2, AnyObject, any, "">'.
  The types of 'default(...).fields.test1' are incompatible between these types.
    Type 'Reference<unknown> | ISchema<{ input?: any; }, AnyObject, any, any>' is not assignable to type 'Reference<unknown> | ISchema<Test1, AnyObject, any, any>'.
      Type 'ISchema<{ input?: any; }, AnyObject, any, any>' is not assignable to type 'Reference<unknown> | ISchema<Test1, AnyObject, any, any>'.
        Type 'ISchema<{ input?: any; }, AnyObject, any, any>' is not assignable to type 'ISchema<Test1, AnyObject, any, any>'.
          Type '{ input?: any; }' is not assignable to type 'Test1'.
            Property 'input' is optional in type '{ input?: any; }' but required in type 'Test1'. ts(2322)

Current (undesired) fix:
```
import { ObjectSchema, mixed, object } from 'yup';

interface Test1 {
  input?: any;
}

const test1Schema: ObjectSchema<Test1> = object({
  input: mixed().required(),
});

export interface Test2 {
  test1: Test1;
}

export const test2Schema: ObjectSchema<Test2> = object({
  test1: test1Schema.required(),
});
```

**Expected behavior**
Unless I'm using Yup wrong, I shouldn't need to convert `input: any;` into `input?: any;`, right?

Currently using yup version 1.1.1

**Additional context**
If you need my tsconfig file, let me know.

**Comment by jquense** [comment]
`any` does really unintuive things to values around it that are sort of out of my control. In part because `any` includes `undefined` and `null` which yup needs to treat as distinct from the type of a field in order for `nullable()` and `defined()` to work. This is partyl because you can't say something is `NonNullable<any>` in TypeScript, that just produces `any`.

Instead use what `mixed` uses for it's generic value which is `type AnyPresentValue = {}`. It looks weird b/c you'd think `{}` means any object literal, but it doesn't it in TS.
