### ISSUE TITLE
import stopped working

### ISSUE THREAD

**Issue by robertherber** [jquense/yup#218]
I just bumped the package from `0.24.1` to `0.25.1` in a React-Native project and suddenly I can't use module imports anymore:
`import yup from 'yup'`

I'm getting:
`undefined is not an object (evaluating '_yup2.default.object')`

It works if I use:
`const yup = require('yup')`

But it's a bit frustrating since it's the only module I can't seem to use import for. Any suggestions / others with the same issue?

**Comment by onurozkan** [comment]
#214 solved my problem

**Comment by jquense** [comment]
Check the changelog, the default import was removed and only named imports now, `import * as yup from 'yup'`

**Comment by lookfirst** [comment]
@jquense 

Treating the semantic MINOR version like a MAJOR, is a real bummer. Having random weird errors crop up after updating my dependencies is more stress. I'm clearly not the only one here.

From https://semver.org/:
`MINOR version when you add functionality in a backwards-compatible manner, and`

The removal of the default export caused me to have to go and `fix` all my imports, which I wouldn't say is a `backwards-compatible` change. 

Not only that, but since I'm using typescript, the typings haven't been updated, so I have to then make the change without getting the actual benefit (#221). `import blah from 'yup/lib/blah';` doesn't work for me until the typings are updated. So now I have to go and fix things two times.

**Comment by denkristoffer** [comment]
@lookfirst 

True, but Yup is still 0.25 which signifies an unstable API that might change. It's actually a part of semver as well: https://semver.org/#spec-item-4

**Comment by lookfirst** [comment]
Awesome. So, we have an excuse to continue frustrating developers who use our software?

**Comment by jquense** [comment]
Sorry you are showing up to complain that I'm not following semver and then when some ponted that i am actually, you are also annoyed? I'm sorry changing the API has annoyed you but it's unreasonable for you to think breaking changes where never going to happen, especially on pre 1.0.0 software. That said the version was bumped predictabling to indicate the breaking change in the way commone for node and just package ecosystem. Both yarn and npm wouldn't auto increment your yup version unless you told them to explicitly bump up. You it's always frustrating to get code breakage, but you can't blame me because you didn't bother to check what the changes were, or take the time to understand the versioning (which, again, is stricter then speced semver to help you avoid this) thanks

**Comment by lookfirst** [comment]
Thanks for maintaining a useful library. Seriously. I know how much work it is. Users never 'take the time' to do anything. They expect to download the code and just have it work. They expect people to tell them when they are going to break things.

This tone is exactly why people complain about the node dependency ecosystem. Of course I just updated my dependencies, which is why I got into this mess. I do this routinely because of constant issues like this, it happens over and over and over again every time I update. Last week it was `MUI 1.0` screwing all my imports. Before that, it was `create-react-ts` suddenly depending on a new file. Before that, brew updated me to node 10 and some dependency 5 levels deep broke. It's endless and I'm terrified of getting so far out of date that it'll take me a week of `fixing` things. Why should I, as a stupid user, have to live in fear of upgrades?

Instead of thinking about ways to make things less tragic for developers, you just get all blah blah that this is pre-1.0 software and I should have checked the changelog of every dependency update. Thanks for proving my point.

`yup` has been around since Apr 2015, has ~42k weekly downloads on npm and 29 contributors. If anything, you're neglecting that it could have been made 1.0 ages ago... you know... to explicitly indicate it was a breaking change. To be honest, I question why this change wasn't made long ago... anyway...

Any reason why you couldn't just tell people to migrate for a few versions first? Maybe even go as far as adding a better explanation to the changelog. How to diagnose and resolve the issue quickly and easily?

Don't bother answering, it isn't worth either of our time. I've made my point.

**Comment by jquense** [comment]
I did indicate that it was a breaking change by adding a changelog entry, pr-ing docs downstream, and bumping the left most non zero version, according to the idiomatic and most common versioning pattern in the ecosystem this library is a apart of. 

Again you are complaining to me about not being familiar with this pattern, while also suggesting that you shouldn't have be responsible for understanding changes in your direct dependencies. While I do regret this caused you frustration, I'm don't feel any pressure to match your, atypical, expection for how versioning and OSS maintaining should work thanks.
