### ISSUE TITLE
Ignore value in transform

### ISSUE THREAD

**Issue by you-fail-me** [jquense/yup#219]
Is it possible to transform a value in a way that yup will treat it as not set? How?

I want to have a behavior that if I e.g. type certain characters, they are not accepted by the form, the typing event is totally ignored and things behave as if nothing was typed

**Comment by jquense** [comment]
that sounds like something that is best handled in the change function of your form. Yup can't really ignore a value in the way you want since it doesn't have any awareness of the last value, only the value you passed in to transform. You can not transform an input by adding `.strict()` to the field but that probably won't give you the outcome you are thinking of
