### ISSUE TITLE
Date 1970-01-01T00:00:00Z is not validating.

### ISSUE THREAD

**Issue by moltar** [jquense/yup#234]
It looks like a valid date, and standard JS Date object can parse it.

```js
new Date('1970-01-01T00:00:00Z')
```

However, `yup` validator fails:

https://runkit.com/moltar/5b293e490d95e300127736f4

> TypeError: The value of createdOn could not be cast to a value that satisfies the schema type: "date". 
> 
> attempted value: "1970-01-01T00:00:00Z" 
> result of cast: null

Thanks!

**Comment by moltar** [comment]
Just tried Node.js repl, works fine too:

```
> new Date('1970-01-01T00:00:00Z')
1970-01-01T00:00:00.000Z
```

**Comment by jquense** [comment]
The date uses a "loose" ISO 8601 parser, which is not the same as what the browser may or may not be able to parse. We don't use `new Date(value)` as a fallback because it can produce clearly "wrong" results that are hard to detect like: `new Date(null)` should be an invalid date but in Chrome its `Wed Dec 31 1969 19:00:00 GMT-0500`

If you are comfortable with those results or want to provide your own parsing you can consumize the schema

`myDate = () => date.transform(useDateContstructor)`

and then use `myDate()` throughout your code

**Comment by moltar** [comment]
Sure, but it still does not make the `1970-01-01T00:00:00Z` date invalid, regardless of how you parse it. Why closing the issue?

**Comment by jquense** [comment]
Bah! sorry i missunderstand waht the actual error was here. You are right this is a bug, parsing is returning `0` and doing a too loose falsey check on it

**Comment by iroy2000** [comment]
For right now, if you want to do validation, seems like you need to use regex to make sure it is a iso string

yup.string().matches(/\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z)/, { excludeEmptyString: true })

https://www.w3.org/TR/NOTE-datetime

**Comment by linux-nerd** [comment]
Do we have any release plan for this issue?
