### ISSUE TITLE
Unable to resolve "@babel/runtime/helpers/builtin/extends"

### ISSUE THREAD

**Issue by IlyasAbdighni** [jquense/yup#281]
Hi Guys, today I am having the error
```
 Unable to resolve "@babel/runtime/helpers/builtin/extends"
```

Does anyone know how to solve this? 

Yup version: 0.26.2

**Comment by IlyasAbdighni** [comment]
Sorry guys, my own problem. The new version 0.26.2 actually works.

**Comment by mellis481** [comment]
Just to add to this since I'm still confused by the auth's posts... I ran `npm install --save yup` myself just now and, for some reason, it installed version 0.26.0.  That was the version that was throwing the babel-related runtime errors.  FWIW, I'm using Typescript as my transpiler.  After reading this, I changed the version in my package.json file to 0.26.2 and that resolved my babel-related errors.
