### ISSUE TITLE
Add between method

### ISSUE THREAD

**Issue by vladshcherbin** [jquense/yup#352]
It would be nice to have `between` method, to group min and max calls together. Example:

```js
const schema = yup.string().min(18).max(30);
```

into

```js
const schema = yup.string().between(18, 30);
```

What do you think about this little addition?

**Comment by vladshcherbin** [comment]
@jquense would be great to have some kind of a reply in addition to just closing :(

**Comment by jquense** [comment]
I think it's worth not including this and save some bytes. If you like the shorthand it's easy to add in your own app via 
```js
yup.addMethod(yup.string, 'between', function between(min, max) {
  return this.min(min).max(max)
}
```

**Comment by vladshcherbin** [comment]
@jquense saving some bytes actually made me smile. Yep, I'm okay with custom method since this issue got only a few upvotes, thank you :)

**Comment by vonagam** [comment]
I think concern about size is normal one, but also desire and expectation to have some other common (but less common than others) helpers/validators.

There is a way to satisfy both - extensions. Files which will not be required in `index.js`, so if you `require('yup')` or `import * as yup from 'yup'` they will not be included. But they may be required for usage directly. Imaginary example for `string.between`:

```js
import * as yup from 'yup';
import between from 'yup/string/between';

between( yup.string, yup.setLocale ); // now yup.string() has between method
```

I think there are many bonuses to including such extensions: achievement of parity with joi, providing default localisation, tests. Also if people use such official extensions instead of custom ones then when you introduce some breaking changes they have less to worry about.
