### ISSUE TITLE
Bundle size vs. Install size

### ISSUE THREAD

**Issue by shellscape** [jquense/yup#359]
Hey there. Stopped in to evaluate the lib after a colleague recommended it. I'm opening this issue to raise a curiosity. While `yup` is much smaller (by about 42kb) than `joi`, it's nearly 3 times larger of an install, and it looks like the dependencies chosen are the culprit.

I noticed that `@babel/runtime` in in `dependencies` rather than `devDependencies`. On the surface that looks like an error, since I couldn't find where the runtime was being used in `dist` nor `lib` on a cursory search.

The big culprit on the install size seems to comes from `lodash`. And while there is a perfectly valid use-case for `lodash` here, it could be said that such a large dependency isn't actually needed. Looks like the primary use for it is: https://github.com/jquense/yup/blob/dd474ff79fb34aee5780dc0aebeac42eb6b88e48/rollup.config.js#L14-L21. And that's cool, but most of those methods are now available as part of ES5/6, and for the ones that aren't, much smaller one-off modules are available which do the same. For the clientside bundles, `lodash` could be used as a polyfill and kept part of `devDeps` instead.

Anyhoo, I'm a fan of lean-and-mean, and this was a curiosity. Cheers 🍺

**Comment by jquense** [comment]
Hey there, I'm usually not much a fan for optimizing install size ahead of runtime size, performance or ease of maintenance. Part of the problem with even trying to optimize this is that choices may actually make things worse overall when not taken together in the context of the ecosystem. 

`@babel/runtime` (seen [here](https://unpkg.com/yup@0.26.6/lib/index.js)) _reduces_ runtime size by providing reusable helpers instead of inline them in each function. For something like `lodash` we do use it as a runtime dependency in a few places and same deal, instead of rewriting a bunch of common utils myself we use lodash, and the main lodash package, because it's very likely that some other package in your app bundle _also_ uses lodash. Overall you get a smaller app bundle because yup uses lodash (in most cases).

**Comment by jquense** [comment]
It should be said that Joi doesn't have to worry about this as much a pure node module, tho likely it's still faster to install using lodash since yarn/npm can dedupe that package and install it only once, again because almost all ndoe/web applications use lodash _somewhere_

**Comment by jquense** [comment]
> If anything, reducing the library's reliance on a massive package and getting up it to speed on the latest developments and not having to be concerned about those utils sounds a lot like it would reduce the maintenance burden, protect against future tech-debt, and future-proof the library.

writing and maintaining a bunch of utils, or sourcing, evaluating and installing a bunch of different modules is significantly more of a maintenance burden than using lodash. Beyond Lodash is one of the most heavily used packages in the js ecosystem (15,191,575 weekly installs), and JD Dalton is one of the most responsive devs doing OSS. Any bugs are likely to fixed immediately vs Bob Doe's `pick` module which may never be updated again. 

Again This is sort of an odd discussion without a good reason to even want to optimize this. We are talking about reducing the size of the module on disk, not runtime size or performance. Your major suggestion is to remove lodash but, doing so would _cost_ things elsewhere and I haven't seen a good argument for why optimizing the install size of the package is even valuable.

**Comment by shellscape** [comment]
I appreciate your replies, however I disagree with your position nearly in entirety. I believe I've made a good case for why a change in direction will benefit your project moving forward. That said, best of luck, and I'll pass your responses onto the team.

**Comment by divmgl** [comment]
It's interesting that this hasn't come up more often. I have to agree with @shellscape. Currently working on a new frontend application, decided to add `yup` and to my surprise the minified bundle size grew 67kb. I think bringing in `lodash` modules rather than all of `lodash` is a good start.

**Comment by shellscape** [comment]
@divmgl we switched to https://github.com/hapijs/joi back in November after this issue, similar chaining constructs. anyone not using a build process with a bundler that supports tree shaking get hosed by lodash being included, and there are many, many situations in which that is true. not to diminish the benefits of `yup` in the slightest, we just found `joi` to be a little more flexible project to work with, in both code and community.

**Comment by jquense** [comment]
ya'll to be clear again, yup is not including all of lodash. It's also not depending on treeshaking, in fact we structure imports so that they are the smallest possible _without_ needing treeshaking. This issue was originally only about the size of yup *on disk* when installed not the size of the library when included in an app. Glad you found JOI useful, it's a great project. I'd be interested what was the deciding factor ultimately considering joi is a larger library on disk and when bundled.

I'm _always_ open to reducing the bundled size of yup if anyone has ideas for how to do that more, please suggest them but messing with lodash is not one of those things, we've already optimized that

**Comment by lytc** [comment]
I also suggest that we should move lodash to peerDependencies!

**Comment by GLObus303** [comment]
Any plans on moving lodash to peerDeps?

**Comment by jquense** [comment]
no there is no plan. that is an actively incorrect way to use peer dependencies and i am not doing it.
