### ISSUE TITLE
How to allow empty string for Yup.number()?

### ISSUE THREAD

**Issue by gangstaJS** [jquense/yup#360]
How to allow empty string for Yup.number()?

**Comment by sudarshanch** [comment]
May be this will help you https://github.com/jquense/yup/issues/298 ?

**Comment by gangstaJS** [comment]
@sudarshanch yes it was help me, thx

**Comment by arkinem** [comment]
```
  const schema = yup.lazy((value) => {
      if (value === '') {
        return yup.string();
      }

      return yup.number();
  });
```


or one-liner:

```
const schema = yup.lazy((value) => (value === '' ? yup.string() : yup.number()));
```

**Comment by guilhermemoretto12** [comment]
@arkinem Hi, how could I use that inside `Yup.object().shape({...})`?

**Comment by Renato6GS** [comment]
@guilhermemoretto12 Something like this
const schema = object()
  .shape({your_name: lazy((value) =>
      value === ''
        ? string()
        : number()
            .typeError()
            .positive()
            .max(9999)
            .integer()
            .required()
  }).required();

**Comment by MhamedMonastiri** [comment]
@guilhermemoretto12  sure,

```
  const schema = Yup.object().shape({
    field: Yup.lazy((value) =>
      value === ''
        ? Yup.string()
        : Yup.number()
    ),
  });
```

**Comment by guilhermemoretto12** [comment]
@MhamedMonastiri that seems a cleaner solution, thank you

**Comment by rstarkov** [comment]
`transform` seems like a better approach:

    .number()
    .transform((val, orig) => orig == "" ? undefined : val)

This converts empty strings to `undefined` and non-empty strings are either parsed as usual or result in a typeError.

**Comment by ahmedkhabar** [comment]
**I tried all the solutions here **and this is the conclusion**
if you are using React hook form or Formik with TypeScript, use the lazy approche because it will fix the default type error and also the real time error (when the user start typing).

`yup.lazy(value => value === ""
        ? yup.string().required("Product price is required")
        : yup.number().required("Product price is required").positive("Product price should be positive");)`

**Import Notes:**
if your field not required remove .required()
I use it twice in because if you don't add it to yup.string(), it will pass even if the user doesn't add any value
This approche also use the yup.number(), so you have every number validation such as positive, min, max...

I hope my comment was helpful and thanks to everyone participate to solve this issue. ❤❤
