### ISSUE TITLE
More strict email validation

### ISSUE THREAD

**Issue by victordidenko** [jquense/yup#386]
We use yup for client-side validation, and [class-validator](https://github.com/typestack/class-validator) for server-side validation. Class-validator uses [validator](https://github.com/chriso/validator.js) for email validation.
And in some cases email passes yup validation, but fails on server side.

For example `13malinator@wwe.j`

Is it possible to make email validation more strict?
Or should I create issue for validator.js, because email above, frankly speaking, looks like valid according to RFC? But from real world's point of view, this is obviously incorrect email.

**Comment by inpendio** [comment]
Yep, same problem here...

**Comment by jquense** [comment]
you can use whatever regex you'd like with a custom test to match any server logic. I will say, in all likelihood we'll either remove or make the existing test **less strict** in the future, since validating email via a regex is very fraught. You're example above, for instance is definitely a valid email address technically. 

Overall the only real way to validate an email, is to send an email to it and require the user respond.

**Comment by victordidenko** [comment]
Thing is that [validator](https://github.com/chriso/validator.js/blob/master/src/lib/isEmail.js) doesn't use single regex to test email, so it is impossible to write one to match logic...

**Comment by jquense** [comment]
you can use `isEmail` itself in a custom test if you want

**Comment by schmod** [comment]
One glaring omission (which QA folks are incidentally really good at exposing) is that Yup allows email addresses with more than 64 characters before the `@`.

I think we might be able to bolt that onto the regex that Yup uses without meaningfully increasing the size of the library...

**Comment by ahce** [comment]
@jquense why closed this?
I started use yup and get this problem.
I think the same as this [comment](https://github.com/jquense/yup/issues/386#issuecomment-456514231)
