### ISSUE TITLE
How to use it synchronously ?

### ISSUE THREAD

**Issue by fpetitit** [jquense/yup#42]
Hi,
I would like to use Yup to validate forms in a ReactJS application, but synchronously to simplify the code.
Is there a way to make synchronous validation ?

Thanks.

**Comment by jquense** [comment]
There isn't any way to validate synchronously right now, since any validation could be async (such as a validation against the server). That being said it shouldn't be much more complicated to do the validations in React

```js
handleFormChange(model) {
  mySchema.validate(model)
    .then(validated => this.setState({ model })
    .catch(error => doSomethingWithErrors(error.errors))
}
```

if you'd like to use something that already handles all that for you I would check out [react-formal](https://github.com/jquense/react-formal)

**Comment by AnAppAMonth** [comment]
@jquense I use redux-form and it requires sync validators for client-side validation. Do you have plans to support sync validation for the client side? Thanks.

**Comment by lloydh** [comment]
+1 also trying to use with redux-form
