### ISSUE TITLE
defining labels after schema using reach

### ISSUE THREAD

**Issue by foxhound87** [jquense/yup#425]
I'm trying to set the labels when the schema is already defined using reach in this manner:

```javascript
const yup = require("yup");

const values = {
  name: 0,
  age: 20,
};

const schema = yup.object().shape({
    name: yup.string().required(),
    age: yup.number().required().positive().integer().max(18),
});

yup.reach(schema, 'name').label('Custom Label Name');
yup.reach(schema, 'age').label('Custom Label Age');

schema
    .validate(values)
    .then($values => console.log('success', $values))
    .catch($errors => console.log('errors', $errors));

```

https://runkit.com/foxhound87/defining-labels-after-schema-using-reach

but the custom label is not working, I still see the property names.

how can be achieved?
maybe I'm doing something wrong?

Thank You

**Comment by jquense** [comment]
Yes, making any change to a schema produces a new schema, since they are immutable. In your case above you add a label to a schema but don't do anything with the return, the original schema is unchanged so when you validate it you don't see the labels. You need like a setIn method  which isn't included in yup but I think there was a version of one somewhere in a similar issue

**Comment by timc13** [comment]
can you provide more color?  Oftentimes, we have defined schemas, but we want to define new schemas based on the existing one, where only one field is different.  Something like this seems like it would be very useful.
