### ISSUE TITLE
yup.number().nullable() does not allow `null` value

### ISSUE THREAD

**Issue by gastonovic** [jquense/yup#500]
`const quantity = number().positive().nullable();` does not work for me in case of `quantity:null` this input gives me this error  

> quantity must be a `number` type, but the final value was: `NaN` (cast from the value `NaN`).
ValidationError: quantity must be a `number` type, but the final value was: `NaN` (cast from the value `NaN`).

**Comment by eddyw** [comment]
Hey, you must pass a boolean value as argument to `nullable`
```javascript
const quantity = number().positive().nullable(true);
```

**Comment by mattleonowicz** [comment]
I have the same problem. nullable() is the same as nullable(true), so that's not the solution.

**Comment by eddyw** [comment]
```javascript
quantity = number().positive().nullable()
quantity.validateSync(null) // No error

quantity = number().positive().nullable(false)
quantity.validateSync(null) // Error
```
If you check the original validation error, it has a property called `params` which should contain something like:
```javascript
  params:
   { path: 'this', // or e.g 'someNestedObj.quantity`
     value: NaN, // <<<<<<<<<< when cast to number
     originalValue: null, // <<<<<<<<<< before cast to number (original)
     label: undefined,
     type: 'number' }
```

`originalValue` should contain the original .. value that was passed before Yup tried to cast it to number. Are you sure that what you're passing (as `originalValue`) when using `nullable(true)` is in fact `null`? I work on a project which has all types as nullable (including number) and it works well as expected. 

I did encounter the issue when a value coming from an input was empty string (which is, of course `NaN`). If it happens that you want certain values such as empty string to be considered `null`, you can use `transform` first, something like:

```javascript
const quantity = number().positive().nullable(true /* or false */).transform(v => v === '' ? null : v)
```
In which case, if `nullable(true)`, then empty strings would also be valid. Otherwise, empty string would be transformed to `null` but fail if `nullable(false)`

**Comment by mattleonowicz** [comment]
I debugged what was wrong in my case, and actually I really did pass NaN to yup, so it was my fault. So the errror message was right after. My fault was assuming that the error message must have been wrong! :D

**Comment by simoami** [comment]
In my case, the value is an empty string, as a result of clearing an input field. I have the field defined as `Yup.number().min(0).default(0)`. I was expecting the cast operation to convert the empty string to 0. Sort of like `+0 || 0` but instead it gave me the nasty NaN error. 

It looks like this was intended: https://github.com/jquense/yup/blob/1c1844293c69db5307b04764f20af3bbeaf8f265/src/number.js#L19

Only `undefined` fallbacks default. Is this ideal though because `+''` casts to zero, so why exclude it?

**Comment by eddyw** [comment]
@simoami the way I was dealing with it was:
```javascript
number().transform(v => v === '' ? void 0 : v)
```
I think the above makes sense (number.js:19) in that, we wouldn't always want default to `0` when it's an empty string. In my use case, an empty string (from input field) meant `undefined` and not `0`

**Comment by simoami** [comment]
Thanks @eddyw, nice workaround.
> In my use case, an empty string (from input field) meant undefined and not 0
Fundamentally, a numeric cast operation needs to output a number or NaN. so undefined is not in that range. This is similar to typeof always returning a string. It also returns `'underfined'` instead of `undefined`. So `typeof` is honoring the contract and can be trusted to always return a string. Same thing with a numeric cast operation can be trusted to always return a numeric value. Here's some casting examples to use as reference:
```
+'0' -> 0 // a number
+'' -> 0 // a number
+'test' -> NaN
+'false' -> NaN
```
So why deviate from the native js behavior?

**Comment by simoami** [comment]
Perhaps you can borrow from the`.default(...)` value when a cast doesn't work. So `.default(undefined)` would return the same for empty string and `.default(0)` would return 0 for an empty string.

Additionally, you can see how this error is nasty, as the default behavior which is why I came to post about it.

![weird-validation-error](https://user-images.githubusercontent.com/2038264/58655453-19e56b80-82e8-11e9-90da-eb8f37980cca.gif)

**Comment by sibelius** [comment]
I'm having the same problem with yup.string().nullable(), any other way to fix it?

```jsx
field: yup.string().when('type', {
      is: type => type === true,
      then: yup
        .string()
        .required(),
      else: yup.string().nullable(true),
    }),
```

**Comment by jaripekkala** [comment]
If the schema passes the validation I would expect the same value be also castable via the schema.

This isn't the case right now.

```ts
const age = yup.number().nullable();
```

```ts
if (age.validate(null)) {
  age.cast(null); // quantity must be a number type, but the final value was: NaN (cast from the value NaN).
}
```

**Comment by thismatters** [comment]
> ```js
> .transform(v => v === '' ? null : v)
> ```

I used:

```js
.transform((v, o) => o === '' ? null : v)
```

...after noting that `transform` supplies two arguments to the callback, the second being the `originalValue` which was the empty string for me.

**Comment by jquense** [comment]
This seems like a bug in the number tests, which should basically bail if the number is null.

that said if you are dealing with empty string values they will not be coerced to null you'd need to do that yourself

**Comment by igtm** [comment]
same here

**Comment by goremukin** [comment]
Bug is still here

**Comment by haroldjcastillo** [comment]
> > ```js
> > .transform(v => v === '' ? null : v)
> > ```
> 
> I used:
> 
> ```js
> .transform((v, o) => o === '' ? null : v)
> ```
> 
> ...after noting that `transform` supplies two arguments to the callback, the second being the `originalValue` which was the empty string for me.

Also validating the NaN in case of numeric inputs 
```js
.transform((v) => (v === '' || Number.isNaN(v) ? null : v))
```

**Comment by lebadapetru** [comment]
So is this going to be fixed/changed? null, undefined, NaN should trigger the validation only if nullable(false) or required() is present ... and i would like to avoid adding that transform to each number input...

**Comment by nonoumasy** [comment]
I tried using the following parameters/properties on yup so that the 'year', 'month', and 'day' are optional. However, it keeps giving an error message.

```
year: yup
        .number()
        .nullable(true),
    month: yup
        .number()
        .min(1)
        .max(12)
        .positive()
        .nullable(true)
        .transform(v => v === '' ? null : v),
    day: yup
        .number()
        .min(1)
        .max(31)
        .positive()
        .nullable(true)
        .transform(v => v === '' ? null : v),
```

<img width="453" alt="Screen Shot 2021-04-11 at 2 24 18 AM" src="https://user-images.githubusercontent.com/6312676/114298813-06bb8f00-9a6d-11eb-8273-2b0572d6d563.png">

**Comment by qbWithYou** [comment]
> I tried using the following parameters/properties on yup so that the 'year', 'month', and 'day' are optional. However, it keeps giving an error message.
> 
> ```
> year: yup
>         .number()
>         .nullable(true),
>     month: yup
>         .number()
>         .min(1)
>         .max(12)
>         .positive()
>         .nullable(true)
>         .transform(v => v === '' ? null : v),
>     day: yup
>         .number()
>         .min(1)
>         .max(31)
>         .positive()
>         .nullable(true)
>         .transform(v => v === '' ? null : v),
> ```
> 
> <img alt="Screen Shot 2021-04-11 at 2 24 18 AM" width="453" src="https://user-images.githubusercontent.com/6312676/114298813-06bb8f00-9a6d-11eb-8273-2b0572d6d563.png">

I solved this problem like this:
`
number()
        .transform((currentValue, originalValue) => {
            return originalValue === '' ? null : currentValue;
        })
        .nullable()
        .typeError('Must be a number')
`

**Comment by albertcito** [comment]
It works for me:

```javascript
 coverage: Yup
        .number()
        .required('Coverage is required')
        .transform((currentValue, originalValue) => (originalValue === '' ? undefined : currentValue))
        .min(minCoverage)
        .max(maxCoverage),
```

**Comment by lomberas** [comment]
> ```js
> number().transform(v => v === '' ? void 0 : v)
> ```

Were you able to fix this? I am also dealing with this issue.

**Comment by lomberas** [comment]
> I'm having the same problem with yup.string().nullable(), any other way to fix it?
> 
> ```js
> field: yup.string().when('type', {
>       is: type => type === true,
>       then: yup
>         .string()
>         .required(),
>       else: yup.string().nullable(true),
>     }),
> ```

Were you able to fix this? I am also dealing with this issue.

**Comment by lkotan** [comment]
> > ```js
> > .transform(v => v === '' ? null : v)
> > ```
> 
> I used:
> 
> ```js
> .transform((v, o) => o === '' ? null : v)
> ```
> 
> ...after noting that `transform` supplies two arguments to the callback, the second being the `originalValue` which was the empty string for me.

Thanks it worked for me :)

**Comment by Moinax** [comment]
Hi guys,

Why is this issue closed.

The simple fact that clearing an input field with `type="number"` should not throw an "Invalid value" message as @simoami showed.

Why should we have to use a `transform` method to fix this everytime we have a number field ?

**Comment by quyle92** [comment]
here is what works for me to define nullable field with `when` prop:
```
const imageValidator = (nullable) =>
 yup
        .mixed()
        .when([], {
            is: () => !nullable,
            then: yup.mixed().required(),
            otherwise: yup.mixed().notRequired(),
        })
```

**Comment by Aissa-cmd** [comment]
for me this solution worked for me
```javascript
const schema = yup.object({
  price: yup
    .number()
    .nullable(true)
    .typeError()
    .transform((_, val) => val ? Number(val) : null)
})
```
in this case the `price` field is optional

**Comment by boryscastor** [comment]
I am upgrading from 0.39 to 1.x and seeing this issue. I have a pretty simple schema with min and max values, where min and max are optional and either of them is required if another is provided:

```
field_min: Yup.number()
    .nullable()
    // .transform(value => (Number.isNaN(value) ? null : value))
   .when('field_max', ([fieldMax], fieldSchema) => {
      if (fieldMax === null) {
        return fieldSchema;
      }

      return fieldSchema.required();
    }),

  field_max: Yup.number()
    .nullable()
    // .transform(value => (Number.isNaN(value) ? null : value))
    .when('field_min', ([fieldMin], schema) => {
      if (fieldMin === null) {
        return schema;
      }

      return schema.required().moreThan(fieldMin);
    }),
```

Initial values are correctly set to null for both fields. But for some reason when Yup gets the value of max in min validation, it converts null to undefined and casts it to NaN (Number(undefined) = NaN).

Only this magical transform helps.
