### ISSUE TITLE
addMethod / Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by marcosjuniorzup** [jquense/yup#521]
I am trying to add an array method to validate if the item is unique, however it is returning this error:
```
formik.esm.js:742 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at yupToFormErrors (formik.esm.js:742)
    at formik.esm.js:266

```
My code:
```
const schema = yup.object().shape({
    environment: yup.string(),
    entities: yup.array().of(
      yup.object().shape({
        key: yup.string().required(),
        chips: yup.array().required().uniqueItem('errorMessage')
      }).required().uniqueProperty('key', 'message')
    )
  })
```

```
export function uniqueItem(message) {
  return this.test('unique', message, function testItem(arrayValues) {
    const {
      path
    } = this

    if (arrayValues.some(item => arrayValues.include(item))) {
      throw this.createError({
        path: `${path}`,
        message
      })
    }
    return true
  })
}

Yup.addMethod(Yup.array, 'uniqueItem', uniqueItem)```

**Comment by DaddyWarbucks** [comment]
I believe this is due to how validations run in parallel. When using `test`, you cannot assume that the value is present because `required` may or may not have run yet. Instead you need to check for the presence of a value before operating on it.

Note lines 10-12 in this link: https://runkit.com/daddywarbucks/5cb8bca650be5200128a4e15

**Comment by sibelius** [comment]
check my comment here https://github.com/jaredpalmer/formik/issues/929#issuecomment-490611548

this happens because your validation function is throwing an error
