### ISSUE TITLE
Question: yup schema from flowtype

### ISSUE THREAD

**Issue by rosskevin** [jquense/yup#53]
Case: react-formal + yup + flowtype

I see a lot of potential schema duplication between yup and a flowtyped object.  It was on my list to look at, but I bumped into https://github.com/seanhess/runtime-types

Do you have any thoughts on a yup schema for use with react-formal derived from flowtype using runtime-types to get the metadata?

Am I thinking about this all wrong?  Easier way? Just too hell bent on writing code once?

**Comment by jquense** [comment]
There are certainly some fun schema generation somewhere, but I'm not sure you gain a lot from the flow types. since you still have to write the validations, which seems like it'd lead to the same possible errors/mistakes/time taken, as straight up duplication.

Also not quite sure how you might add the validations later for nested things...hmm. I do think its  fun area to explore tho. If you think it's valuable i'd be happy to offer any input, but I don't use flowtype generally so I'm not a likely user

**Comment by rosskevin** [comment]
Related info from runtime-types:
https://github.com/seanhess/runtime-types/issues/9#issuecomment-224680613

You may be right about metadata regarding validations, also i18n for validation messages.  I'll keep these in mind as I try to figure out the right solution.  

yup + react formal was quite simple and useful, and I'm not set yet in having the need to define these types outside of forms...so I don't yet know if integration of a flowtype is _needed_.  Given the answer from runtime-types, it's definitely doable.

I'm using relay mutations for changes, so the instance provided by yup/react-formal is all I need so far.

Thanks!
