### ISSUE TITLE
False positive validation(?)

### ISSUE THREAD

**Issue by ppseprus** [jquense/yup#57]
Hey!

Schema validation is a rather new topic for me so this might be just me missing something...
I wanted to validate JSON and XML data against a Yup schema. For this I use `JSON.parse()` and `JXON.stringToJs()`.

I found this url to test xml alidation with Yup:
https://www.w3.org/2003/05/soap-envelope/

The data gets parsed as a JavaScript object but when I validate it against a **wrong** schema it does not throw any errors to the console. It simply returns the object I'm validating.

    const YUP_OPTIONS: {
        strict: true,
        abortEarly: false,
        stripUnknown: false,
        recursive: true
    };
    var schema = yup.object().shape({ randomStuff: yup.string() });
    var parsedResponse = jxon.stringToJs(response);
    schema.validate(parsedResponse, YUP_OPTIONS, (error, value) => {
        // error === null
        // value === the parsedResponse
    });

Obviously, I skipped tons of stuff...
You can check out the repository though:
https://github.com/ppseprus/endpoint-validator/blob/master/validator.js#L63

Thanks for taking the time!

**Comment by jquense** [comment]
hi there, it's hard to see what might be the problem because the example is incomplete. what is the yup schema you are using and what values are failing to validate correctly?

**Comment by ppseprus** [comment]
Would be awesome if I could include Yup in a "JSFiddle"...
Anyhow.. The schema is what I actually wrote above:

    var schema = yup.object().shape({
        randomStuff: yup.string()
    });

I intentionally passed in a wrong schema to see if it would fail, but the error variable is null and the original JavaScript object gets returned.

**Comment by ppseprus** [comment]
I found an alternative to JSFiddle, but I think you have to reg. to see the code running
https://ide.c9.io/ppseprus/yup-test

**Comment by jquense** [comment]
;) https://tonicdev.com/570c52590a85f71200eb09ba/yup

**Comment by jquense** [comment]
I think I see your problem though. By default object schema don't just reject values that aren't exactly the same shape as the schema, this is intentional, often times data contains extra fields that you can safely ignore because its not relevant to the bits you care about validating. 

In your case the single `randomStuff` field is also not going to throw any errors since it doesn't have an validations associated with it. You could make it `string().required()` and I bet It would fail. Also if you do want to assert that the value is exactly, and only the shape you define you want to use the [`object().noUnknown()`](https://github.com/jquense/yup#objectnounknownonlyknownkeys-boolean--true-message-string-schema) method

**Comment by ppseprus** [comment]
WOW! Totally working now! Thanks!
I thought I missed something along the way, but could not figure out what!
Thanks again! : )

**Comment by jquense** [comment]
glad to help

**Comment by rotexhawk** [comment]
Yup should be as restrictive as possible because it is better to fail early and that's the whole point of validation. With no sql databases it is quite easy for an unknown field to make it all the way to db. To make things worse passing the strict flag to `validate` also doesn't check for this anomaly.
