### ISSUE TITLE
.reach() + .isValidSync() not working when using when() condition

### ISSUE THREAD

**Issue by AlberErre** [jquense/yup#590]
Hey there!

I'm facing an issue when using .reach() + .isValidSync() inside a when() condition.

Basically I have this schema:
```
  (.... more schema up here)

  registrationCode: yup
    .string()
    .required()
    .isRegistrationCode()
```

where `isRegistrationCode()` is:
```
yup.addMethod(yup.string, "isRegistrationCode", function(
  this: yup.StringSchema,
  message = "must be correct code"
): yup.StringSchema {
  const REGEXP = /^([ce]?\d{4}[a-z0-9]{3})$|^([a-z0-9]{1,2}\d{4}[a-z0-9]{1,2})$/i;
  return this.matches(REGEXP, message);
});
```
I evaluate this condition using `reach()` on my app as follows:
```
    const isValidCode = yup
      .reach(schema, "registrationCode")
      .isValidSync(6122BBB);
```
In my case, isValidCode returns a boolean that I can use to apply further logic. 
**Under this schema**,  `.reach() + .isValidSync()` **works like a charm**.

**However**, I had to do a refactor, adding a `When()` condition. 
So now my schema is as follows:
```
  (.... more schema up here)

  registrationCode: yup
    .string()
    .required()
    .when("isRegistered", {
      is: true,
      then: yup
        .string()
        .isRegistrationCode()
    })
```

-------

Expected behaviour:
Under this new schema, `isValidCode` should return `false` or `true` depending on the regular expression.

--------

Current behaviour: 
Under this new schema, `isValidCode` returns `true` no matter what. My assumption is that `isRegistrationCode()` is not evaluated inside the `When()` condition.

---------

Is there a reason why custom  `yup.addMethod` functions are not evaluated when using `reach()` inside a `when()` condition?  

**is this supported?** 

Thanks!

**Comment by jquense** [comment]
The behavior you are seeing makes sense right? How would `registrationCode` know how to resolve the when condition, since you've not provided it with a value for the dependent field `isRegistered`? `registrationCode` is only using your isRegistrationCode method _when_ some other field is `true` but that field doesn't exist in the context of just validating the one field.

In generally you probably want to use `validateAt()` which combines reach and validate but requires the root object as the passed in value ensuring the validation can resolve correctly. You can also do it manually by passing in `parent` in the options

**Comment by AlberErre** [comment]
Thank you very much ^^
I thought reach() method passed the entire schema context, but focusing on that piece particular piece, it's much clear now.
