### ISSUE TITLE
using "when" to validate if parent condition is met is not working 

### ISSUE THREAD

**Issue by matwming** [jquense/yup#595]
Hi, below is my data structure:

`const initianValue={
 trustFund: {
    isTaxResidentOther: false,
    controllingPersons: [
      {
        id: "person1",
        surname: "",
        givenName: ""
      }
    ]
  },
}`

I want to make surname required if "isTaxResidentOther" is true, below is my validation schema:
```
const validationSchema = yup.object().shape({
  trustFund: yup.object().shape({
    controllingPersons: yup.array().of(
      yup.object().shape({
        surname: yup.mixed().when("trustFund.isTaxResidentOther", {
          is: true,
          then: yup.string().required("Surname is required!"),
          otherwise: yup.string().notRequired()
        })
      })
    )
  })
});
```
Even if I change "when" to `when("isTaxResidentOther"`
it is still not working. I did some research but still cannot figure out how to do it.

I think if I move  ` isTaxResidentOther: false` out of 'trustFund' object it should be working.

**Comment by RichardYan314** [comment]
the `keys` argument of `.when` specifies path to sibling / sibling decendents . but the `isTaxResidentOther` is in the parent of `controllingPerson` object.

If you try

``` js
surname: yup
  .mixed()
  .when('trustFund.isTasResidentOther',
    function(this, isTasResidentOther, schema) {
      console.log(isTasResidentOther);
      return schema;
  })
```

you will see `isTaxResidentOther` is `undefined`.

I found a way around this, but it is not very elegant.

First, we get `initianValue.trustFund.isTaxResidentOther` and put it in the validation context.
since this field may not exists, I used the lodash `_.get` function to avoid exception.

``` js
validationSchema.validateSync(initianValue, {
  context: {
    isTaxResidentOther: _.get(initianValue, 'trustFund.isTaxResidentOther')
  }
});
```

We also need yup to varify `initianValue.trustFund.isTaxResidentOther` exists and is boolean.

```
const validationSchema = yup.object().shape({
  trustFund: yup.object().shape({
    isTaxResidentOther: yup.boolean().required(),
    ...
  })
});
```

yup's exception is more understandable than something like `Cannot read property <...> of undefined`.
that is why I used lodash.

And finally grab this value from the validation context:

``` js
surname: yup.string().when('$isTaxResidentOther', (value, schema) =>
  value ? schema.required("Surname is required!") : schema.notRequired()
)
```

notice I used a different `.when` signature, so I am adding on top of the current schema.
you can choose to do it differently (like using `yup.mixed()` and replace it with `yup.string()` in `.when` as you did).

putting everything together:

``` js
const initianValue={
  trustFund: {
    isTaxResidentOther: false,
    controllingPersons: [
      { id: "person1",
        surname: "",
        givenName: "" } ] }, };

const validationSchema = yup.object().shape({
  trustFund: yup.object().shape({
    isTaxResidentOther: yup.boolean().required(),
    controllingPersons: yup.array().of(
      yup.object().shape({
        surname: yup.string().when('$isTaxResidentOther', (value, schema) =>
          value ? schema.required("Surname is required!") : schema.notRequired()
        )
      })
    )
  })
});

// This is validated
validationSchema.validateSync(initianValue, {
  context: {
    isTaxResidentOther: _.get(initianValue, 'trustFund.isTaxResidentOther')
  }
});

// this gives `ValidationError: Surname is required!`
initianValue.trustFund.isTaxResidentOther = true;
validationSchema.validateSync(initianValue, {
  context: {
    isTaxResidentOther: _.get(initianValue, 'trustFund.isTaxResidentOther')
  }
});
```

Notice this only works because you only need the raw value of `trustFund.isTaxResidentOther` in `.when`.
If you plan to transform it, you have to do it before where I used lodash instead in the schema, and only use yup to test it.

---

There is another way of doing this: at the ancestor of `surename` which is a sibling of `isTaxResidentOther`, use `.when` to dynamically mutate the schema for `surename` with closure.
I will make an attempt once I get sometime later this day.

**Comment by RichardYan314** [comment]
``` ts
const initianValue={
  trustFund: {
    isTaxResidentOther: false,
    controllingPersons: [
      { id: "person1",
        surname: "",
        givenName: "" } ] }, };

const validationSchema = yup.object().shape({
  trustFund: yup.object().shape({
    isTaxResidentOther: yup.boolean().required(),
    controllingPersons: yup
      .array()
      .when('isTaxResidentOther', (isTaxResidentOther, schema) =>
        schema.of(yup.object({
          surname:
            isTaxResidentOther ?
              yup.string().required() :
              yup.string().notRequired()
        }))
      )
  })
});

// This is validated
validationSchema.validateSync(initianValue);

// this gives `ValidationError: trustFund.controllingPersons[0].surname is a required field!`
initianValue.trustFund.isTaxResidentOther = true;
validationSchema.validateSync(initianValue);
```

**Comment by truongtv22** [comment]
thanks you

**Comment by matwming** [comment]
Hi RichardYan314, thanks for your solution. The second solution works perfectly. Your help is appreciated.
