### ISSUE TITLE
Can yup return the error string instead of Schema object or boolean?

### ISSUE THREAD

**Issue by powerfulj** [jquense/yup#604]
Can yup return the error string instead of Schema object or boolean? I cannot find the API.

Thanks guys
CJ

**Comment by jquense** [comment]
I don't really understand the question. What error string? It throws any errors so you need to `catch` it when using validate

**Comment by chengjia080787** [comment]
sorry bro it’s my bad. The validate will return the original input as string even if it passed the validation.  What I want is that if the validation passed. It can return a null or undefined or empty string instead of the original input. If it failed then it returns the error message. Is this possible or not? Thanks

**Comment by jquense** [comment]
Validate returns the cast input value not the original value (whatever the type is not just strings). Short answer, no there is no API that works like that but if that format is important to you you can wrap the validate call, catch the error and return it or return null
