### ISSUE TITLE
2 fields sum should not be greater than 100 validation

### ISSUE THREAD

**Issue by jjayaraman** [jquense/yup#659]
I have a cross-field validation in which the sum of 2 fields should not exceed 100
How can I do this, please?

I tried this, but did not work

`
		/** yup validation schema */
		const schemaFields = {
			percentDilutionInputValue: yup.number()
				.typeError('Please enter a valid number')
				.required('Dilute % is required')
				.min(0, 'Minimum atleast 0')
				.max(100, 'Allowed maximum is 100'),
			percentWeighedInputValue: yup.number()
				.typeError('Please enter a valid number')
				.required('Weighed % is required')
				.min(0, 'Minimum atleast 0')
				.max((100 - yup.ref('percentDilutionInputValue')), 'Total should not exceed 100 %')
		}
`

**Comment by privateOmega** [comment]
@jjayaraman I feel this doesn't work because you are passing an expression `100 - yup.ref()` as an argument to function which accepts either the value `100` or `yup.ref`. And AFAIK yup.ref() is evaluated at validation time which might be the sole cause of your issue.

Anyway I have rewritten your code to use `test()` to replicate the `max()` according to your need.
Find the sandbox [here](https://codesandbox.io/embed/max-with-ref-o6hxj). Hope it helps.

PS: It would be nice if you could paste formatted code next time 💯 

@jquense Taking in expressions consisting of refs and values instead of just either value or ref seems like a very reasonable use case.  Is it at all possible to attain this even though I am aware that ref resolution happens at validation/cast time?

**Comment by minservr** [comment]
thank you. It was helpful for me.
