### ISSUE TITLE
String URL validation regex false positive with double slashes

### ISSUE THREAD

**Issue by SimonB407** [jquense/yup#672]
**Describe the bug**
Regex used when validating URL has 1st capturing group `^((https?|ftp):)?` which is optional, but after that there is match for `\/\/` which is mandatory. This is causing any URL without `http:// | https:// | ftp://` at the beginning to not be valid, but URL like `//example.com` to pass validation.

**To Reproduce**
https://repl.it/repls/IntrepidScentedMonitors

**Expected behavior**
URLs like `//example.com` should **not be** valid
URLs like `example.com` should **be** valid

**Platform (please complete the following information):**
 - Browser Chrome, Version 72.0.3626.121
 - Version of yup 0.27.0

**Possible solution**
Current regex: `^((https?|ftp):)?\/\/(...`
Fixed regex: `^((https?|ftp):\/\/)?(...`

**Additional**
Regexes inserted in regex101 (v1 is current one, v2 is fixed one) https://regex101.com/r/jlZoAO/2

**Comment by vatosarmat** [comment]
Looks like a dup of https://github.com/jquense/yup/issues/562. Maybe `new URL` is better for URL validation than regexp

**Comment by kdgyimah** [comment]
> Looks like a dup of #562. Maybe `new URL` is better for URL validation than regexp

@jquense Please update on this?

**Comment by WaifuForever** [comment]
I believe this is not intended to behave this way and should be fixed, quoting @jquense "sure happy to use the URL if it's available, but fallback to the regex otherwise"

In this stackoverflow question there are some regex options that might suit your needs, one thing to keep is regex doesn't check the validity of the domain: https://stackoverflow.com/questions/61634973/yup-validation-of-website-using-url-very-strict
