### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by jhalborg** [jquense/yup#684]
Hey 👋

Thanks for a great lib! 💪

It'd be awesome if it could be converted to TS so types were automatcally mainated along with the code, instead of relying on a separately and community maintained `.d.ts` file on DefinitelyTyped 👍

Would that be a reasonable request? 😄

**Comment by jquense** [comment]
So while i'm fan of typescript and use it other projects. I don't actually think there would be much value in converting this project to TS. The reason being that it'd be very hard to type correctly with the current API. My guess is the typing would actually get worse than the current DT types, because they can just declare how the schema work without needing to statically prove it in the code.

**Comment by jquense** [comment]
I am open to making the official types supported better tho if someone wants to move them here.

**Comment by jhalborg** [comment]
Having the types being part of the package would be the next-best thing if typing the library is not an option. I'm not sure I follow your logic about the library being typed leading to worse types than separately maintained ones, but I think it'd make a lot of sense to maintain a `.d.ts` file in this repo and make sure it updates along with any API changes.

**Comment by sgronblo** [comment]
Yes I agree.

1. It's much easier to manage the workflow of updating the types if they are managed inside a repository.
2. It allows you to include the correct index.d.ts with the library so users don't need to figure out which version of @types/yup is compatible with which yup version.

**Comment by jquense** [comment]
@sgronblo yup has been written in typescript for almost a year

**Comment by sgronblo** [comment]
Oh oops. We are on a pretty old version it seems. Never mind.
