### ISSUE TITLE
Confused regarding async

### ISSUE THREAD

**Issue by ericclemmons** [jquense/yup#7]
Hi!  This lib looks good, but I'm a bit confused...

The docs mention that validation returns a Promise (or a callback if specified), but I'm not seeing _why_ that's the case, as one of the validation types seem asynchronous.

For example, checking `email` against an API to ensure it hasn't already been registered is async.  Is that possible, or not supported?

**Comment by jquense** [comment]
in a validation function (`. test()`) you can return a promise and it will just work. so rather then returning true/false you can return a promise that resolves true false. So your email example is definitely supported but you need to 'build' it yourself with the test method. 

let me know if that helps, otherwise i'd be happy to give some clearer examples as soon as I have access to something other than my phone!

**Comment by jquense** [comment]
ok. laptop in hand maybe I can tap out a coherent answer to your question. All built in validation tests 'resolve' asychronously even if they don't need to. This is an intentional deisgn choice so that the api can handle custom validation tests that need to be async without releasing Zalgo.

so in your example you might do something like this:
```js
var email = yup.string().test('check-email, 'this email is already taken', function(value){
  return fetch('/ckeckname', { email: value })
    .then( resp => resp.responseText === 'true')
})
```
where fetch returns a promise that resolves `true` or `false`. yup understands that you returned a promise (or called the callback for the node style) and waits until the promise resolves to see if the test passed or not,

**Comment by ericclemmons** [comment]
Thanks for the answer!

A major project is using `js-data-schema` for validation, since Joi doesn't support async (yet: hapijs/joi#307), but this library is much smaller.

Starred :)
