### ISSUE TITLE
Can't validate 2 fields depending on each other, cycled dependency

### ISSUE THREAD

**Issue by SirajKakeh** [jquense/yup#706]
I have two fields: `min_price` and `max_price`
<img width="283" alt="Screen Shot 2019-11-26 at 2 49 47 PM" src="https://user-images.githubusercontent.com/25347947/69635780-d634aa00-105d-11ea-833e-e4fb039dfca7.png">
I have to validate the two as such:

- if the two values are entered, min should be less and max should be greater, otherwise should be at least 10 and at max 1000

and have this code for it:

```
Yup.object().shape({
  min_price: Yup.number().when("max_price", max_price => {
    return max_price ?
      Yup.number().min(10).max(max_price)
      : Yup.number().min(10).max(1000);
  }),
  max_price: Yup.number().when("min_price", min_price => {
    return min_price ?
      Yup.number().min(min_price).max(1000)
      : Yup.number().min(10).max(1000);
  }),
});
```
I'm having cycled dependency error and where ever I look I can't find the solution, I tried adding `[min_price, max_price]` or `[[min_price, max_price]]` as a second parameter to `shape` but this also didn't work, can you please help with this case?

 - Browser Chrome
 - Version 78

**Comment by jquense** [comment]
https://repl.it/@jquense/AnguishedTemptingAutomatedinformationsystem seems to work with the second arg?

**Comment by jonallured** [comment]
One thought you might try: use the `context` option to pass into the `when` functions what's going on. Something like:

```ts
const values = {
  max_price: 100,
  min_price: 10
}

const context = {
  max_price,
  min_price
}

const options = {
  context
}

const Schema = Yup.object().shape({
  min_price: Yup.number().when("$max_price", max_price => {
    return max_price ?
      Yup.number().min(10).max(max_price)
      : Yup.number().min(10).max(1000);
  }),
  max_price: Yup.number().when("$min_price", min_price => {
    return min_price ?
      Yup.number().min(min_price).max(1000)
      : Yup.number().min(10).max(1000);
  }),
});

Schema.validateSync(values, options)
```

Note the "$" in the first position of `when` - that tells Yup to use the context rather than sibling attributes. So the idea here is to "freeze" the values of max and min price in the context and then pass that into the when functions to avoid any sort of cyclical dependency. Good luck!

**Comment by dalawwa** [comment]
To expand on @jonallured answer, if you believe it is an interesting feature, I will try to open a PR whose aim is to `try catch` the `cyclic dependency` error in order to create the `context` and consume it, but I am not totally sure yet, how to achieve it.

Big thanks to all contributors, love this community.
Cheers
