### ISSUE TITLE
schema.cast reverses order of keys in objects

### ISSUE THREAD

**Issue by rheidari** [jquense/yup#707]
**Describe the bug**
Keys are being reversed when casting an object.

**To Reproduce**
https://repl.it/@rheidari/yup-reversing-keys

**Expected behavior**
Expect the keys defined in the schema to be the same order coming out when cast.

**Platform:**
Node v8.16.0

**Additional context**
Noticed that there's a `.reverse()` being called in sortFields. When I remove that it acts as expected, however I'm sure you had a reason for it being there https://github.com/jquense/yup/blob/1426feceb6c5544c526711bedcf388afaf6115b9/src/util/sortFields.js#L31

**Comment by jquense** [comment]
this is expected. Because fields can depend on the cast values of other fields to determine their own shape (e.g. `when()`) we need to make sure the dependent fields are cast and processed before the fields that depend on them. The `reverse` call gives us nodes in the correct order when there are dependencies, tho it has the effect of also just reversing insertion order for schema with no interdependencies. This is theoretically avoidable, but I don't think it's worth the extra work and complexity to ensure the new object has keys inserted in the same way.

**Comment by rheidari** [comment]
Thanks for the explanation @jquense. Is there a way I can best go about re-ordering the cast object so that the original order of fields is maintained as per the schema, or will I need to do that outside of yup? I tried implementing a `transform()` on each object to recreate the object ordered by the `Object.keys(schema.fields)` but that didn't seem to have any effect.

In my case I have a deeply nested object that will need to retain the order defined in each yup schema as I'm going to be transforming it back into XML.

**Comment by rheidari** [comment]
Here's an example of what I've done to sort the cast object post `yup.cast`, is there a better way to do this so that it's done during the `yup.cast` rather than after the fact?

https://repl.it/@rheidari/yup-sort-by-schema-keys

**Comment by david-golightly-leapyear** [comment]
It would definitely be a great benefit to preserve the key order. I wonder if this could be achieved in Yup with a simple second `reverse` on each object after the casting is complete?

**Comment by sodaru-it** [comment]
+1 
I could observe this in `getDefault()` call also .

**Comment by TacianoBack** [comment]
You can try this in your validate function.

	const shape = {
		name: yup.string().max(100),
		email: yup.string().max(60).email(),
	}

	const newShape = Object.entries(shape)
		.reverse()
		.reduce((prev, [key, value]) => ({ ...prev, [key]: value }), {})

	const schema = yup.object().shape(newShape)
