### ISSUE TITLE
When will version 1.0 be released? :)

### ISSUE THREAD

**Issue by codler** [jquense/yup#714]
When will version 1.0 be released? :)

**Comment by jquense** [comment]
idk why does it matter?

**Comment by codler** [comment]
It will mark that this library is stable and not beta.

**Comment by jquense** [comment]
Luckily it's not in beta. the versioning follows the npm/node convention of breaking changes bumping the leftmost non 0 number. So there is not a lot of functional difference when installing between pre v1 or post. you have the same semantic versioning contact either way.

I'll bump it to v1 at some point but it's not supper important at the moment

**Comment by sidewaysgravity** [comment]
I would agree that a 1.0 release would be nice. It took me a minute to figure out why my yup package wasn't updating before I realized npm treats sub 1.0 releases different depending on how you include the package. So ^0.27.0 does not update to the latest 0.28.0 when it would if it was a 1.0 release or greater. It is also recommended to start at 1.0. https://docs.npmjs.com/about-semantic-versioning

Thanks for all the work on the package. I can work with the sub 1.0 versioning as well, I just need to modify how I state the requirements in my package.json file.

**Comment by Levino** [comment]
This is very important. You release practically all the time as "breaking" and everybody has to update the version number by hand. If you would go from `1.33` to `1.34` however everybody would get the update it they depend on `^1`. This really does not work for `^0`. `0.33` and `0.34` are considered incompatible.

**Comment by IanVS** [comment]
It also gives for more fine-grained information, since you can distinguish between patch releases which don't add any features, and minor releases which do.  That's not possible when using only the last two numbers.  And there's no reason you can't keep making breaking changes after 1.0.0, you'll just end up with a high major version number, which is totally okay.

Just as an anecdote, I'm only now hearing about yup and deciding if I want to use it.  Seeing a `0.x` version number made me nervous, so I searched the issues to see if I could find a thread like this, discussing what it will take to get the library to "stable."  You may be losing users who are uncomfortable using a package less than `1.0.0`.
