### ISSUE TITLE
Unexpected behaviour when using .transform() and .max() on Date

### ISSUE THREAD

**Issue by klimnikova** [jquense/yup#817]
**Describe the bug**
I am trying to validate date and when the value is empty string set it to null in order to make the field required. Also I'm adding .max() method. So when I try to transform my value, using .transform(val, originalValue)  originalValue comes as my maxValue, not the original one, which is "".

**To Reproduce**
```
birthDate: Yup.date()
    .nullable()
    .transform((value, originalValue) => {
      if (originalValue === "") return null;
      return dayjs(value).isValid() ? value: null;
    })
    .max(dayjs().subtract(18, 'year'), 'too young')
    .required('required'),
```

**Expected behavior**
expected that I will recieve originalValue that comes from input

**Platform (please complete the following information):**
 - Browser any
 - 0.28.2

**Comment by jquense** [comment]
please post a runnable illustration using the issue template thanks!

**Comment by klimnikova** [comment]
[![Edit silly-minsky-0nyee](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-minsky-0nyee?fontsize=14&hidenavigation=1)
Attached the example, thanks

**Comment by jquense** [comment]
sorry what are you expecting to happen here. `originalValue` is whatever the input was, in this case you are passing a dayJS date object, not an empty string. Your transform needs to convert items to js Date objects for the date schema to work

**Comment by klimnikova** [comment]
[![Edit silly-minsky-0nyee](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-minsky-0nyee?fontsize=14&hidenavigation=1&theme=dark)
okey, but why when I pass in input empty string and  in console.log I got two values : maxDate and empty string? According to you it should be an empty string... may be I just don't undrestand how the transform()  fully works..

**Comment by jquense** [comment]
it is any emptyString if the input is an empty string, you can see in the console. It's failing to be valid because you marked it as `required` which makes sense because it's now `null`.

transforms are a set of functions that are passed the result of the last transform so the `console.log` here is reporting the result from the built in transform, e.g something like `Date.parse("")`. `originalValue` is different in that it's _always_ the first value in the chain, in case a transform upstream, like the built in coercion logic fails, you can still get the original value to try something else

**Comment by klimnikova** [comment]
okey, I got it. thanks a lot!
