### ISSUE TITLE
yup.string validates object as true.

### ISSUE THREAD

**Issue by FinnFrotscher** [jquense/yup#821]
```
(async value => {
  console.log(
    "validated", 
    value, 
    await yup.string().isValid(value)
  );
})({this: "that"});
```
yields
```
  validated 
  Object { this: "that" }
   true
```

**Comment by jquense** [comment]
that's b/c it's first casting the object to a string. The issue is that in JS most anything can be coerced to a string, and it's hard to generally tell if that stringification is a good one. Numbers for example will yield `NAN`, dates `InvalidDate`, as ways of knowing if the coercion failed, but strings always succeed, and rather than accidentally rejecting valid transformations, we accept some invalid ones, since it's easier to extend yup to reject those than it is to fix false negatives.

That said, it might be worth trying to detect _clear_ errors like `{}` -> `"[object Object]"` if simple and foolproof, but it doesn't exist right now

**Comment by jquense** [comment]
also you can disable casting before validation by doing `string().strict()` and then it will only accept string values
