### ISSUE TITLE
Timestamp validation error

### ISSUE THREAD

**Issue by potty** [jquense/yup#848]
**Describe the bug**
When trying to validate timestamp, valid timestamp obtained from `date.getTime()` is not validated correctly by `date()` fn.

**To Reproduce**

https://codesandbox.io/s/gracious-torvalds-1oyln?file=/src/index.test.js

**Expected behavior**
When I put the timestamp into Date constructor as `new Date(timestamp)`, I'll get valid `Date` object so I expect, that validation will also pass. Couldn't find any info about timestamps in tests, by from docs if I understand that correctly, lib is validating date by putting the value into Date constructor, so I don't get it why this is not working.

**Platform (please complete the following information):**
 - Browser: Chrome 84, Mac OS
 - Version: Yup 0.28.4

**Comment by jquense** [comment]
Date parsing current only works for ISO formatted strings, and things that are already Dates. It should maybe also assume numbers are timestamps, but i'm not sure that's a good idea at the moment...

In the meantime you can handle your case via a transform, with something like:

```js
date().transform(function (castValue, originalValue) {
  return this.isType(castValue) ? castValue : new Date(originalValue)
})
```

**Comment by jthn** [comment]
I know this is an older issue, and I'm happy to create another if warranted. I also totally respect that this is a really slippery issue based mostly on how funky Date is.

Per the snippet above, as of 0.32.9, by the time the transform gets called, if a ms since epoch timestamp was provided, it already is an instance of Date, so to get this to work for me I had to do:

```
date().transform(function (castValue, originalValue) {
  return Number.isNaN(originalValue) ? value : new Date(originalValue)
})
```
I have it working for my particular use case, so there isn't necessarily anything to do, but the docs (and the code) tell a somewhat confusing story.

From the docs:

> The default cast logic of date is pass the value to the Date constructor, failing that, it will attempt to parse the date as an ISO date string.

After reading this, I also saw that the min/max values didn't accept numbers, but in my use case I'm receiving a `number` so I figured I try it and see if it worked. It does work, however the logic is inverted based on what the documentation indicates.

Based on how I'm reading the docs, the input should be passed to `new Date(value)` _before_ being parsed as an ISO Date.

But looking at the [DateSchema constructor](https://github.com/jquense/yup/blob/master/src/date.ts#L30-L40), `isoParse` gets called first, which calls `Date.parse` with the input if it doesn't match the ISO 8601 regex. I _think_ if it was changed around to:

```js
      this.transform(function (value) {
        if (this.isType(value)) return value;

        if (!isNaN(value)) return new Date(value)

        return isoParse(value);
      });
```

The behavior would match the docs.
