### ISSUE TITLE
thoughts

### ISSUE THREAD

**Issue by mpal9000** [jquense/yup#9]
Hi, nice lib! Some thoughts:
- `stripUnknown` option, wich is undocumented, should take effect even if `strict` is set to `true`.
- an `allowUnknown` option, that throws on unknown properies when set to `false` (like in Joi), would be nice
- a `func()`, `alternatives()` and `object().pattern()` validators would be nice too
- is it worth to make this more modular ie. requiring validators separately and have something like `use()` in the main export? This could help to control the file size (client-side) and allow to have as many validators as you want (built-in), without being all in a single export. This loading style could be also an alternative to the "combo" (current) one *
- error messages would be more user friendly without the `this.` prefix of keys
- in some cases the type casting should be done after validation eg. `yup.number().integer().min(2)` with a given value `''` (empty string) returns `must be at least 2`. Maybe it's better to return `must be an integer`
- `yup.number().integer()` without a given value returns `must be an integer` (without `strict`). Maybe it's better to not return any error, because there is no `required()` rule

```javascript
  // *

  // combo style
  import yup from 'yup';
  const schema = yup.string();

  // modular style
  import yup from 'yup';
  import string from 'yup/string';
  yup.use(string);
  const schema = yup.string();

  // modular style (even better)
  import string from 'yup/string';
  const schema = string();

**Comment by jquense** [comment]
Hi there,

Thanks for taking the time to post your feedback, it is appreciated.

1. I can see where you are coming from here but I don't think I agree that `stripUnknown` should work in `strict` mode, since `strict` means "don't do any parsing" of which deleting properties counts as for me

2. Sounds reasonable, though I am not quite sure how that would work, it is purely a validation that fails when there are extra properties?

3. alternatives would be nice but would add a buuunch of code that I am not sure is worth it. I am still trying to see if there is a simple/perfomant way to do that. `yup` is meant to be fairly extensible (unlike joi) so I try and keep the core more minimal, with the expectation that people will add, and extend for their own needs, the recently added `yup.addMethod()` makes this easier, that and the schema objects are jsut normal constructor functions so you can make new types (like `func`) really easily by inheriting from `mixed`.

4. that's a good question. If all  you want to require specific types you can totally do that! `var string = require(yup/lib/string`)`. requiring specific validations is harder though, in theory `yup` is structured to allow that very easily, the `addMethod()` api makes it even easier. I haven't seem a big need though practically, because the validations are pretty small code-wise in most cases, and at a certain point making a user import and add them gets  a bit hostile to the dev experience, plus one of the main points of the library is validation so having none included by default seems annoying.

5. I agree, the default messages are really meant for developers, if you want to make them user facing the recommendation is to override them, but I could do a better job documenting how to do that globally. The main reason they aren't more friendly upfront is that if you do want them to be user facing _most_ people are going to want to customize them anyway, and many will need to localize them to specific languages.

6. This is sort of a quirk of the way it is structured, the reason you don't get "must be an integer" is because the value is an integer 'b/c `''` coerces to `0`. I tend to think this is the 'correct' behavior but there are so many valid opinions in this area. As of right now there is no good way of having certain validations run before transforms, and it would be a fair amount of work to restructure the code to handle that, and I am not sure how much of a benefit it was add.

7. hmm you are probably right, this also matches how min/max work. I will fix it!

**Comment by mpal9000** [comment]
1. 

2. with this one, I think that there is no need for `1.` From Joi's docs:

  >  when true, allows object to contain unknown keys which are ignored. Defaults to false.

  The `abortEarly` option still has effect when is `false`
3. these are the methods that kept me away from replacing all my "Joi" schemas with "Yup". I would like to see this library as an isomorphic fork of Joi + async validation + custom rules (at least for now). That's why I added this to the list. Maybe this is not what you are targeting for, but right now it is very frustrating what you have to do to make Joi work in a browser, without being larger than the whole app. I thought this library could solve that. About the file size, after implementing more built-in methods, I think `4.` can provide a solution
4. I generally think for client-side libraries, that having good control of what you are importing, is more important than a few more lines of import statements. Also separating in directories and files doesn't mean that those are not built-in. They will be included by default
5. leaving out that prefix would allow someone to use the message directly to the UI. I think that `this` doesn't offer anything when you read the message in a UI or in the terminal

**Comment by jquense** [comment]
2. I think we can get `allowUnknown` in no problem, although the default will be the opposite as joi, ie. it will default `true`, no really reason to break back compatibility here for that, and tbh I prefer allowing unknown keys by default

In general `yup` is not trying to be a drop-in replacement for `joi` partly because all those features are exactly the thing that makes it really hard to get working in the browser. Also the additional flexibilty and extensibility makes its much harder to keep api parity, so I am not really trying. The goal is to remain _close_ so that it is easy enough to move between them. I think that `alternatives` will be added to yup at some point, since that is a pretty major feature of joi, but I don't have a lot of time to make that happen right now  and I don't use alternatives personally (pull requests welcome tho). 

You can definitely add `func` in your own code really easily, just look at how `bool` is implemented. and I think you shouldn't have to much trouble implementing `object.pattern` as well maybe something like this

```js

yup.addMethod(yup.object, 'pattern', function(pattern, schema, message) {
  
  this.test('pattern', message, function(value, path, context) {
    var known = Object.keys(this.fields)
        , tests = []

    for (var key in value) if (value.hasOwnProperty(key) ) {
      if ( known.indexOf(key) !== -1 ) continue
      if ( pattern.test(key) ) 
        tests.push(schema.isValid(value[key]))
    }

    return Promise.all(tests)
        .then( results => return results.every(r => r === true) )
  })
})
```

**Comment by mpal9000** [comment]
All right, I just didn't wan't to maintain these basic methods but I'll think about it :-) Again, nice library and I'm sure it will get even better!
