### ISSUE TITLE
How can i validate that only numbers are in a string?

### ISSUE THREAD

**Issue by R45H** [jquense/yup#927]
Ok, i have this solution:

```
const digitsOnly = (value) => /^\d+$/.test(value)

Yup
    .string()
    .test('Digits only', 'The field should have digits only', digitsOnly)
```

But this is so strange, is there really no solution out of the box?

**Comment by jquense** [comment]
`string().matches(/^\d+$/)` is the builtin method for doing a regex match. There isn't any built-in method for checking if a string is actually a number, but you can add your own 

```
yup.addMethod(yup.string, 'integer', function () {
  return this.matches(/^\d+$/, 'The field should have digits only')
})
```

**Comment by xegulon** [comment]
@jquense why not implement a `yup.string().numeric()` into the lib (for credit card inputs for example)?

**Comment by jquense** [comment]
The core library doesn't need to include everything. It makes the core bloated for folks that only need basic validations. Instead yup is easily extensible so you can add one if you need it

**Comment by olegKusov** [comment]
> The core library doesn't need to include everything. It makes the core bloated for folks that only need basic validations. Instead yup is easily extensible so you can add one if you need it


this case occurs frequently. it will be good to have builtin validation that checks that string has only numbers

**Comment by sajera** [comment]
I propose that Yup implements a feature enabling users to switch validation methods, such as 'integer', to apply numerical validation rules to strings. For instance, rather than being limited to using 
`yup.number().min(0, 'Must be bigger than 0').required('Is mandatory')`
 exclusively for numbers, we could utilize it for strings as well.

This enhancement would be beneficial for scenarios where the validation logic for numbers also applies to strings. It would simplify the validation process and enhance the flexibility of the Yup library.

Personally, I'm unsure about how to create such a method using `yup.addMethod`

**Comment by MoSattler** [comment]
Also looking for something similar - basicly the equivalent of `.pipe(z.number())`.

**Comment by leecheuk** [comment]
Not sure this helps, [`yup-numeric`](https://www.npmjs.com/package/yup-numeric) validates whether a string is a valid number.

CASE 1: Whether string is integer
```ts
import { numeric } from 'yup-numeric';

const schema = numeric().integer();
const value = '1.0000000000000000000000000000000000001';

const result = await schema.validate(value); // rejects
```

CASE 2: Whether string value is less than 1.0000000000000000000000000000000000002
```ts
import { numeric } from 'yup-numeric';

const schema = numeric().lt('1.0000000000000000000000000000000000002');
const value = '1.0000000000000000000000000000000000001';

const result = await schema.validate(value); // resolves
```
