### ISSUE TITLE
How to pass error message received from the backend to the error object?

### ISSUE THREAD

**Issue by 4eshircat** [jquense/yup#957]
I use **react-hook-form** library and **yup** to validate the form.
If form is valid I submit it to the server and may receive a validation error back, for example "This email address is already in use".
How can I pass this text to output an error below the email input using its name?

Waiting for you answer. Thank you 🙏🏻

**Comment by jquense** [comment]
I don't really know how RHF works, so that's really more of a question for that library since it's not really related to yup. If you want to make the server error part of your schema, then you can create a custom `test()` that calls the server to check the name and if it's invalid uses `this.createError` to add the server message, https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema
