### ISSUE TITLE
Priority of [ typeError vs required ]

### ISSUE THREAD

**Issue by SmileJayden** [jquense/yup#971]
**Describe the bug**

```
// my scheme
yup
    .number()
    .typeError('this is NaN')
    .positive('only positive')
    .integer('only int')
    .required('plz input the value'), // never comes here... 

```
when this scheme meets  an empty string( like `""`),  I expected show error messege of required, which is `plz input the value`.
But actual happen is that the error messege is `this is NaN` (which is `typeError` scheme)

In this case, `required` sechem never comes.

I want to show  `'plz input the value'` message when value is empty.

Thx in advance :)

**Platform (please complete the following information):**
 - Browser [chrome]
 - Version [`"yup": "^0.29.1"`]

**Comment by jquense** [comment]
yes type errors come before others, b/c they have to be run first otherwise all other checks would have to assume that the input is an unknown type

**Comment by SmileJayden** [comment]
So, there is no way to get `required` msg when there is no data?

**Comment by jquense** [comment]
you don't have "no data" here, you have a string value. I think that it makes sense that the error you are getting is that "a string is not a number", instead of "this is required" because there isn't a missing value here at least as far as a number schema is concerned. If you want to treat empty strings as empty values, then i'd suggest transforming them to `undefined` or `null` (if you want to make it nullable), then the type will be correct and you will get the required error. 

Otherwise you can set the typeError() to be "this is required" making the assumption that any incorrect type is an empty value.

**Comment by SmileJayden** [comment]
Thanks a lot for you answer :)

**Comment by strass** [comment]
Hey I think I have a similar problem, I am writing a 'unique' validator that verifies that an array's values are non-duplicated. Right now if there are two empty fields they show up as non-unique errors rather than required. I am using this.createError. Is this the same issue?

**Comment by CaitlinWeb-st** [comment]
For any of those confused like me, don't use `.default(undefined)` use `transform` as described in #634 

```js
Yup.number()
    .transform(value => (isNaN(value) ? undefined : value)) // <---
    .required()
})
```

@jquense This would be really helpful to put into documentation about `number().required()`. I would expect it to transform like this under the hood for `.required()` because otherwise it's essentially ignored/overruled by the `typeError`.

**Comment by rpk-red** [comment]
My code looks like this :
 number()
    .nullable()
    .transform((value) => (value === "" ? null : value))
    .typeError("not a number")
    .required("required filed"),

but still required is never called. Can somebody help?

**Comment by nl5887** [comment]
The `transform` function also accepts a secondary value, originalValue. If you want to have empty values as valid, you can use:

```
let validator = Yup.number()
    .transform((value, originalValue) => {
        return (originalValue === '' ? undefined : value)
    })
    .typeError('Parameter is not a valid numeric value.')
```

**Comment by tankez0r** [comment]
```Typescript
export const EfectivoSchema: formSchemaObjectSchema<IEfectivoSchema> = {
    yupObject: Yup.object().shape({
        efectivo: Yup.number().transform((value, originalValue) => {
            console.log({ value, originalValue })
            return (originalValue === "" ? null : value)
        })
            .nullable()
            .required('This field is required')
            .typeError('this field has to be a number')
    }),


    defaultValues: { efectivo: undefined }
}

```

This works for me in Typescript

The "originalValue" is the value in the field, and  "value" is the interpretation who Yup does when you indicate "Yup.number()". 

So this concludes in this: 
1) You have to transform the values, evaluate if the field value (originalValue) is equals to an empty string. Return null if this is true, and NaN(you can return value, in the case of number, value always return NaN) if this is false.

2)  Set the option nullable: This make nullable as an valid type, because this block TypeError to throw an error.

3) Required recieve the value after the type validation, and it validate the state of the originalValue (null at this point), when it see this is null, it throw or save the error message throwed by required.

I hope it helps you.

**Comment by benevbright** [comment]
> you don't have "no data" here, you have a string value. I think that it makes sense that the error you are getting is that "a string is not a number", instead of "this is required" because there isn't a missing value here at least as far as a number schema is concerned.

However, this is not applied to "required()" the same way.
